### ISSUE TITLE
PL admin performance can be improved

### ISSUE THREAD

**Issue by thelovekesh** [WordPress/performance#1015]
## Summary

PL plugin is using [`plugins_api()`](https://developer.wordpress.org/reference/functions/plugins_api/) to retrieve the data of the standalone plugin from the WPOrg API. 

https://github.com/WordPress/performance/blob/0f110ffe1a50b1d49b4e6309ec311dc6327d304b/admin/plugins.php#L21-L30

Currently, when a user loads the admin page it gets fired  to retrieve the data of each available plugin:
https://github.com/WordPress/performance/blob/0f110ffe1a50b1d49b4e6309ec311dc6327d304b/load.php#L336-L342

Even when the data is retrieved for all plugins, it gets fired again when the user saves the settings or loads the page, and hence page loading time increases.

To avoid hitting the WPOrg API multiple times and reduce the page load time second time onwards, we should consider caching the plugin information for a day or so in the:
- Object cache if present.
- Else, save the response data as transients.

**Comment by westonruter** [comment]
It makes sense to store the plugin info in a transient period. (Remember that when external object cache is enabled then transients are stored on object cache.) Just need to make sure that the cache is varied by the plugins it is fetching or else to vary by the Performance Lab plugin version, so that when a new version is released we will get any new plugins showing up right away.

As for the transient max age, a day may be excessive. Even just 10 minutes would suffice, right? Granted, the information wouldn't be changing often, and if it does, it's likely to coincide with a new PL plugin release anyway. So in that case, an even longer TTL would be fine.

**Comment by thelovekesh** [comment]
@westonruter Since we are fetching data for standalone plugins, do we need to vary its cache by PL plugin version? I think we can simply store it for some time and vary the cache by standalone plugin name.

**Comment by westonruter** [comment]
Storing it for a set period of time (e.g. 1 day) would be fine. 

Why vary the cache by the standalone plugins name?

**Comment by westonruter** [comment]
Oh, because each plugin is queried separately.
