### ISSUE TITLE
Move PL plugin under `plugins/performance-lab`

### ISSUE THREAD

**Issue by thelovekesh** [WordPress/performance#1165]
## Feature Description

As mentioned by @joemcgill in https://github.com/WordPress/performance/issues/1012#issuecomment-1967337536, we should consider moving the PL to plugin to `plugins` dir.

**Comment by joemcgill** [comment]
Thanks for opening an issue for this, @thelovekesh. It would be useful to get a list of all the things that would need to change in order to move PL into the plugins directory. For example, we would need to update our release scripts among other things. 

Treating all of the plugins the same may simplify some things because we wouldn't need to treat PL separately from other plugins, but it would be good to understand how much effort it would be to make this transition before diving in.

**Comment by thelovekesh** [comment]
Thanks @joemcgill. Currently, we're in the midst of decision-making, covering various aspects including the release process. Given this, I believe we can address everything together rather than focusing solely on the efforts required at this moment. Additionally, the build process already supports all necessary tooling and steps for the `plugins` directories.

Thus, aside from the release process, the only task left appears to be relocating the plugin contents to the `plugins/performance-lab` directory and removing PL plugin-specific workflows since all required steps will be covered as part of plugin workflows.

I initiated this now because it's currently causing us to duplicate efforts - once for the PL plugin and again for the rest of the plugins. By relocating the PL plugin to `plugins`, I believe we'll achieve better focus in a single location, both from a developer experience and perf feature addition perspective.
