### ISSUE TITLE
`npm run test-php` failed with error

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/performance#1255]
## Bug Description

Run `npm run test-php` command to run the unit tests for all plugins. It will return error for `performance-lab` plugin.

```
> phpunit '--verbose' '--testsuite' 'performance-lab'
Installing...
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
[29-May-2024 05:17:23 UTC] PHP Fatal error:  Cannot declare class Perflab_Server_Timing_Metric, because the name is already in use in /var/www/html/wp-content/plugins/performance/plugins/performance-lab/includes/server-timing/class-perflab-server-timing-metric.php on line 14
Script phpunit handling the test event returned with error code 255
Script @test --verbose --testsuite performance-lab was called via test:performance-lab
Script @test:performance-lab was called via test:plugins
✖ Command failed with exit code 255
Command failed with exit code 255
```

## Screenshots
<img width="1727" alt="Screenshot 2024-05-29 at 10 51 26 AM" src="https://github.com/WordPress/performance/assets/10103365/2b703dd6-dd81-456f-bc4d-a70ee330e8b4">

**Comment by mukeshpanchal27** [comment]
Ping @thelovekesh as he did similar changes in repo.

**Comment by thelovekesh** [comment]
I just checked the tests in CI, and in the very recent one, the tests are passing - https://github.com/WordPress/performance/actions/runs/9280407570

Let me take a look at my local as well.

**Comment by thelovekesh** [comment]
@mukeshpanchal27 Tests are passing locally as well. On which branch these tests are failing for you?

**Comment by mukeshpanchal27** [comment]
On Trunk branch. Let me destroy the env then try.

**Comment by mukeshpanchal27** [comment]
Working now.

**Comment by westonruter** [comment]
This issue started happening to me. I've opened #1403 to fix.

**Comment by westonruter** [comment]
OK, I seem to have discovered why there is an error. When the `object-cache.php` in tests, the `$plugin_dir` is:

```
/var/www/html/wp-content/plugins/performance-lab/
```

However, when the unit tests are running for `performance-lab`, in the `load.php` the `PERFLAB_PLUGIN_DIR_PATH` is equal to:

```
/var/www/html/wp-content/plugins/performance/plugins/performance-lab/
```

The former directory is mounted from the latter in Docker, and so they are the same directory but from the PHP perspective they are different. So when `load.php` attempts to do:

https://github.com/WordPress/performance/blob/3364bd90bce82aa2b405e8156a7cf2ec2e79243d/plugins/performance-lab/load.php#L34

The `require_once` doesn't work as expected because a separate path to the class was already loaded here:

https://github.com/WordPress/performance/blob/3364bd90bce82aa2b405e8156a7cf2ec2e79243d/plugins/performance-lab/includes/server-timing/object-cache.copy.php#L68
