### ISSUE TITLE
Expose WebP support under Site Health status tab

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#130]
Since not every server environment supports translating JPEG uploads to WebP format, it's worth indicating this to site administrators in an easy-to-understand way. While we already have some basic PHP extension information about image capabilities in the Site Health info tab, it may be worth adding something explicitly about WebP in the Site Health "Status" tab.

For example a message like "WebP images are (not) supported by your server environment", with a brief description on why this is relevant. And potentially a note to "Ask your hosting provider to enable/update xyz"

Also see https://wordpress.slack.com/archives/C02KGN5K076/p1643112555307200?thread_ts=1643041077.295600&cid=C02KGN5K076

cc @adamsilverstein @getsource @spacedmonkey

**Comment by JustinyAhin** [comment]
@felixarntz would it makes sense to add that information in a new tab in Site Health, instead of under "Status".

Asking because it could be related to this issue: https://github.com/WordPress/performance/issues/97. And we might want to have every information output by the performance plugin in one single place.

**Comment by felixarntz** [comment]
@JustinyAhin Potentially, yes. I think we shouldn't block this issue by discussion on the other though, so IMO we could start with showing this in the "Status" tab, and if/once we have a "Performance" tab, update it.

**Comment by kirtangajjar** [comment]
@felixarntz If we end up working on this issue, I would like to work on it if you don't mind :)

**Comment by adamsilverstein** [comment]
I like this idea of having something explicitly showing "WebP support", especially as part of making this the default sub size format. 

For the record, this is where we currently show WebP support, the simplified version might go there as well - under Site Health -> Info -> Media Handling. Maybe we should also show the sub-sized format(s) that WordPress will use?

![image](https://user-images.githubusercontent.com/2676022/151422805-fcb35c3f-d856-4b66-8df7-0fd11609fcdb.png)

**Comment by getsource** [comment]
I do think this makes it pretty clear what formats *are* supported.
Maybe we could display a warning if any of the natively supported formats for resizing are not supported (or, the most common ones folks would notice problems with)?

**Comment by kirtangajjar** [comment]
I was testing this out in my local and I have added this check in the status section for now. If the message sounds good, I can then raise a PR.

![Screenshot from 2022-01-31 18-04-46](https://user-images.githubusercontent.com/8456197/151794938-4cc39c44-dfed-4186-8932-4a02a07499a9.png)

**Comment by getsource** [comment]
I think this sort of message makes sense if WebP as default is enabled with the plugin.
Since if it's not, WebP is not used by WordPress to boost performance.

For the current situation, maybe limiting the message to "Uploading WebP (or whatever other support is missing) files is not supported" would be good?

**Comment by kirtangajjar** [comment]
I have wrote this message keeping in mind that this plugin will eventually get merged into core, so instead of changing the message when we're planning to move it to core, I thought it's better to keep a message assuming WP will be using WebP images to boost performance.

However, for the sake of more preciseness we can show current message when WebP module is activated, and something like "Uploading WebP files is not supported" when it's not.
