### ISSUE TITLE
Incorporate breakpoints into preconnect links added by Embed Optimizer

### ISSUE THREAD

**Issue by westonruter** [WordPress/performance#1341]
> It would be slightly better if the viewport widths were also taken into account, so that an embed only visible on desktop would not get preconnected on mobile. This can be addressed in a follow-up PR.

_Originally posted by @westonruter in https://github.com/WordPress/performance/pull/1302#discussion_r1670865833_

Code in question:

https://github.com/WordPress/performance/blob/84bf4ee2e1033751fdc16beaad1faaeb57e1da5c/plugins/embed-optimizer/class-embed-optimizer-tag-visitor.php#L89-L96

**Comment by ShyamGadde** [comment]
Hi, I've reviewed this issue and have an idea for how to proceed. If it's alright and this issue isn't currently being worked on, could it be assigned to me?

**Comment by ShyamGadde** [comment]
@westonruter I have some questions regarding the merging logic for preconnect links.

Code in question:
https://github.com/WordPress/performance/blob/df29967bfc5eed55a35606595df6344bb4ca9f8c/plugins/optimization-detective/class-od-link-collection.php#L106-L207

I noticed that consecutive links with identical attributes are meant to be merged. However, when breakpoints are introduced, the merging doesn’t seem to occur correctly. Specifically, preconnect links are duplicated across viewport widths:

![Image](https://github.com/user-attachments/assets/c283e3b6-33ac-4378-8824-57ec8c107d37)

Upon examining the sorted links (full log: https://pastebin.com/7eKfdzgt), I found that this duplication arises because the links are only sorted by `minimum_viewport_width`. As a result, links with the same `href` remain separated in the array.

I tried modifying the sorting logic to sort primarily by `href` and then by `minimum_viewport_width`. This change produced the following result:

![Image](https://github.com/user-attachments/assets/1b0473a0-c8e6-44f7-a4f9-7bab397d4d14)

This approach also works for scenarios where embeds should be hidden on specific viewport ranges (e.g., hidden on phablet):

![Image](https://github.com/user-attachments/assets/51b05cc4-59b6-4acf-853e-5ab48d71d8f8)

Could you confirm if my approach aligns with the intended merging logic? Specifically, is it correct to group links by `href` first and then sort by `minimum_viewport_width`? Or is there an aspect of the merging logic I might be overlooking?

**Comment by westonruter** [comment]
@ShyamGadde I think this sounds correct!

**Comment by westonruter** [comment]
The issue didn't come up before because generally only the preload links were being added with media queries. When there are multiple link types and multiple URLs being linked to, it makes sense that the current logic or sorting by the minimum viewport width would be insufficient.
