### ISSUE TITLE
Automatically opt into 1536x1536 and 2048x2048 sizes when generating fallback images

### ISSUE THREAD

**Issue by adamsilverstein** [WordPress/performance#1512]
## Feature Description

As discussed in https://github.com/WordPress/performance/pull/1421 when "generate fallback images" is enabled, we should generate all of the sizes that core generates by default in both mime types (the uploaded type which could be JPEG or PNG and the output type which could be AVIF or WebP). 

This includes two "extra" sizes that were added to the image generation routines later than the original sizes:  1536x1536 and 2048x2048 (typically these are used for high DPI screens).

**Comment by felixarntz** [comment]
For reference: https://github.com/WordPress/performance/pull/1421#issuecomment-2315636957 describes how the opt-in should work, using the approach in the way it's currently intended via "hypothetical" WP core API.

In core, this would happen via the `add_image_size()` calls. Since we're in plugin scope, we would accomplish the same outcome by directly modifying the corresponding global.
