### ISSUE TITLE
Investigate `document.write` usage in WordPress sites

### ISSUE THREAD

**Issue by adamsilverstein** [WordPress/performance#153]
## Description

As part of our work to improve script loading in core, I am investigating how we can improve enqueueing to support and use `defer` for script loading where possible. 

@sgomes explored using `defer` by default in #102 and one issue raised was that for scripts that use `document.write`, adding defer on the script would cause the writing to be ignored (https://github.com/WordPress/performance/issues/102#issuecomment-1016716503).

Opening this issue to investigate if we can use data from httparchive to get a better understanding of how `document.write` is used in WordPress sites. I'm not sure we really have data to get this info so thought I would ask @rviscomi, can we query to get:

* What percentage of WordPress pages enqueue a script that executes document.write? Do we have data around this?
* On these sites, what are the scripts using `document.write`?

**Comment by adamsilverstein** [comment]
Note: this issue came out of a previous discussion, see https://github.com/WordPress/performance/issues/117#issuecomment-1023560829

**Comment by rviscomi** [comment]
37% of WordPress pages (858,134) include a script that contains (but not necessarily executes) `document.write`.
20% of WordPress pages (463,988) include a script that executes `document.write` during the initial page load.

Among the pages that simply contain `document.write`, the most popular domains that serve these scripts are:

script_host | pages | total | pct
-- | -- | -- | --
doubleclick.net | 173,412 | 858,134 | 20.2%
twitter.com | 114,644 | 858,134 | 13.4%
rubiconproject.com | 61,509 | 858,134 | 7.2%
googleapis.com | 60,183 | 858,134 | 7.0%
onesignal.com | 42,598 | 858,134 | 5.0%
googlesyndication.com | 39,258 | 858,134 | 4.6%
pubmatic.com | 16,719 | 858,134 | 1.9%
criteo.net | 16,288 | 858,134 | 1.9%
viglink.com | 13,667 | 858,134 | 1.6%
yastatic.net | 12,219 | 858,134 | 1.4%
ezodn.com | 9,772 | 858,134 | 1.1%
mailmunch.co | 9,112 | 858,134 | 1.1%
stackpathcdn.com | 7,470 | 858,134 | 0.9%
hubspot.com | 7,081 | 858,134 | 0.8%
amazon-adsystem.com | 6,908 | 858,134 | 0.8%
adroll.com | 6,088 | 858,134 | 0.7%
vk.com | 5,755 | 858,134 | 0.7%
taboola.com | 4,762 | 858,134 | 0.6%
sharethis.com | 4,709 | 858,134 | 0.5%
googletagmanager.com | 4,490 | 858,134 | 0.5%

Eyeballing some of these domains, ads and social third parties seem to be the most popular culprits.

We can actually join these domains with the third-party-web dataset to more reliably categorize them:

3P category | pages | total | pct
-- | -- | -- | --
unknown | 618,409 | 858,134 | 72.1%
ad | 390,587 | 858,134 | 45.5%
social | 129,241 | 858,134 | 15.1%
utility | 119,330 | 858,134 | 13.9%
cdn | 80,539 | 858,134 | 9.4%
analytics | 14,676 | 858,134 | 1.7%
marketing | 11,670 | 858,134 | 1.4%
tag-manager | 8,585 | 858,134 | 1.0%
content | 6,004 | 858,134 | 0.7%
other | 4,562 | 858,134 | 0.5%
customer-success | 3,841 | 858,134 | 0.4%
consent-provider | 396 | 858,134 | 0.0%
hosting | 333 | 858,134 | 0.0%
video | 65 | 858,134 | 0.0%

46% of WordPress pages that use `document.write` are because of ads. 72% of pages use it from an unknown source (this could just be a limitation of the third-party-web dataset, which is annotated manually). The next biggest sources are social (15%) and utility (14%) third parties.

Note that the `pct` column isn't expected to add up to 100% since a page may load multiple scripts from various sources that contain `document.write`.

Lighthouse also includes an audit that will flag any scripts that execute `document.write`. This is useful to see which writes are executed during the initial render.

script_host | pages | total | pct
-- | -- | -- | --
doubleclick.net | 182,055 | 463,988 | 39.2%
sharethis.com | 20,860 | 463,988 | 4.5%
googleadservices.com | 20,418 | 463,988 | 4.4%
mailchimp.com | 14,775 | 463,988 | 3.2%
googlesyndication.com | 12,677 | 463,988 | 2.7%
googleapis.com | 12,025 | 463,988 | 2.6%
zopim.com | 7,759 | 463,988 | 1.7%
yastatic.net | 5,392 | 463,988 | 1.2%
amazon-adsystem.com | 3,932 | 463,988 | 0.8%
zohocdn.com | 3,552 | 463,988 | 0.8%
statcounter.com | 2,462 | 463,988 | 0.5%
realsrv.com | 2,356 | 463,988 | 0.5%
rakuten.co.jp | 2,293 | 463,988 | 0.5%
googletagservices.com | 2,204 | 463,988 | 0.5%

Note that the total number of pages is almost half as much as the total from the other methodology (loading a script that contains but not necessarily executes `document.write`). So the relative percentages may not be comparable.

Still, ads and social third parties seem to top the list.

It's interesting that we found ~10k more `doubleclick.net` domains using the "contains and executed" approach than just the "contains" approach, which I'd expect to be more inclusive. One explanation is that we omit any scripts from the dataset of the "contains" approach if they exceed 2 MB.

Also interesting that `twitter.com` showed up second in the top "contains" list but is nowhere in the top "executed". One explanation is that the script isn't executed on the initial page render and it might be written to wait for a certain event like post-load or user interaction. That may make it an especially good candidate for `defer` if it's not already annotated with it.

And here's the same third party categorization using the "executed" approach:

3P category | pages | total | pct
-- | -- | -- | --
unknown | 233,404 | 463,988 | 50.3%
ad | 218,047 | 463,988 | 47.0%
social | 21,808 | 463,988 | 4.7%
cdn | 18,181 | 463,988 | 3.9%
utility | 17,119 | 463,988 | 3.7%
marketing | 16,047 | 463,988 | 3.5%
customer-success | 11,250 | 463,988 | 2.4%
analytics | 6,696 | 463,988 | 1.4%
tag-manager | 1,831 | 463,988 | 0.4%
content | 1,726 | 463,988 | 0.4%
other | 908 | 463,988 | 0.2%
hosting | 890 | 463,988 | 0.2%
video | 44 | 463,988 | 0.0%
consent-provider | 33 | 463,988 | 0.0%

Still mostly unknown and ads 3Ps, but adoption of the other categories have dropped significantly.

<details>
<summary>Queries used</summary>

# ⚠️ BEWARE: Some of these may be very expensive to run!

Getting all pages and script URLs that contain `document.write`, by matching a regex in the raw response bodies:

```sql
WITH wordpress AS (
  SELECT DISTINCT
    url AS page
  FROM
    `httparchive.technologies.2022_01_01_mobile`
  WHERE
    app = 'WordPress'
), document_write AS (
  SELECT
    page,
    url
  FROM
    `httparchive.response_bodies.2022_01_01_mobile`
  WHERE
    REGEXP_CONTAINS(body, r'document\.write\(')
)

SELECT
  page,
  url
FROM
  wordpress
JOIN
  document_write
USING
  (page)
```

Getting all pages and script URLs that execute `document.write`, by parsing the Lighthouse report:

```sql
CREATE TEMP FUNCTION getDocWrites(audit STRING) RETURNS ARRAY<STRING> LANGUAGE js AS '''
try {
  audit = JSON.parse(audit);
  return audit.details.items.map(i => i.source.url);
} catch(e) {
  return [e];
}
''';

SELECT
  page,
  dw_url AS url
FROM (
SELECT DISTINCT
  url AS page
FROM
  `httparchive.technologies.2022_01_01_mobile`
WHERE
  app = 'WordPress')
JOIN (
SELECT
  url AS page,
  report
FROM
  `httparchive.lighthouse.2022_01_01_mobile`)
USING
  (page),
  UNNEST(getDocWrites(JSON_EXTRACT(report, "$.audits['no-document-write']"))) AS dw_url
```

Top script hosts:

```sql
WITH dw AS (
  SELECT
    page,
    url
  FROM
    `httparchive._79a755d33b36bd993bfdbf63f1d172f6c47fb1cb.anond4c73a81_077c_471b_be23_bbee307ae8ac`
), wp AS (
  SELECT
    COUNT(DISTINCT page) AS total
  FROM
    `httparchive._79a755d33b36bd993bfdbf63f1d172f6c47fb1cb.anond4c73a81_077c_471b_be23_bbee307ae8ac`
)

SELECT
  NET.REG_DOMAIN(url) AS script_host,
  COUNT(DISTINCT page) AS pages,
  ANY_VALUE(total) AS total,
  COUNT(DISTINCT page) / ANY_VALUE(total) AS pct
FROM
  dw,
  wp
GROUP BY
  script_host
HAVING
  script_host IS NOT NULL
ORDER BY
  pct DESC
LIMIT
  50
```

Top 3P categories:

```sql
WITH dw AS (
  SELECT
    page,
    url
  FROM
    `httparchive._79a755d33b36bd993bfdbf63f1d172f6c47fb1cb.anond4c73a81_077c_471b_be23_bbee307ae8ac`
), wp AS (
  SELECT
    COUNT(DISTINCT page) AS total
  FROM
    `httparchive._79a755d33b36bd993bfdbf63f1d172f6c47fb1cb.anond4c73a81_077c_471b_be23_bbee307ae8ac`
), thirdparties AS (
  SELECT DISTINCT
    NET.REG_DOMAIN(domain) AS domain,
    category
  FROM
    `httparchive.almanac.third_parties`
  WHERE
    date = '2021-07-01'
)

SELECT
  IFNULL(category, 'unknown') AS category,
  COUNT(DISTINCT page) AS pages,
  ANY_VALUE(total) AS total,
  COUNT(DISTINCT page) / ANY_VALUE(total) AS pct
FROM
  dw,
  wp
LEFT JOIN
  thirdparties
ON
  NET.REG_DOMAIN(url) = domain
GROUP BY
  category
ORDER BY
  pct DESC
LIMIT
  50
```

</details>

**Comment by adamsilverstein** [comment]
Thank you @rviscomi for the detailed analysis, this is super helpful as a reference point in building out better script loading for WordPress.  As we push developers to deprioritize their scripts with defer, it is important to know where we can't do that.

> 72% of pages use it from an unknown source (this could just be a limitation of the third-party-web dataset, which is annotated manually).

Could these be scripts loaded from the sites themselves, ie. from the origin domain?

> Also interesting that twitter.com showed up second in the top "contains" list but is nowhere in the top "executed". One explanation is that the script isn't executed on the initial page render and it might be written to wait for a certain event like post-load or user interaction. That may make it an especially good candidate for defer if it's not already annotated with it.

Twitter winds up getting included as part of a twitter [oEmbed](https://oembed.com/). oEmbeds typically show up as iframes in WordPress, and we add `loading=lazy` to iframes since 5.7. Still, we should probably review oEmbeds more generally to see how they affect performance and if they might be improved.

> Still mostly unknown and ads 3Ps, but adoption of the other categories have dropped significantly. 
So this means these scripts load, but never execute the `document.write`?

**Comment by rviscomi** [comment]
> Could these be scripts loaded from the sites themselves, ie. from the origin domain?

Yes, sorry I had written that in an earlier draft but it got dropped during editing. If the script is loaded from 1P (inline or external script) or any unknown 3P it'll show up as "unknown".

> oEmbeds typically show up as iframes in WordPress

Oh I hadn't considered iframes. That could be another discrepancy between scraping the raw response bodies and using the Lighthouse audit. Maybe LH ignores writes within iframes. Arguably, that's preferable since it doesn't affect the main document.

> So this means these scripts load, but never execute the `document.write`?

Yes, with the caveat above about iframes.

**Comment by adamsilverstein** [comment]
Closing this issue since research is complete for now.
