### ISSUE TITLE
Modern Image Formats: Option to delete the original file on upload

### ISSUE THREAD

**Issue by JosVelasco** [WordPress/performance#1564]
Hi team:

To save disk space, add an option to the settings to delete the original JPEG / PNG.

The file could also be named filename.avif instead of, for example, filename-jpg.avif.

The downsize that I image could be that for images that need to be .jpg or .png for applications like og:image, you'd have to temporarily turn off the option.

**Comment by AhmarZaidi** [comment]
Hey 👋, I'd like to work on this issue!

**Comment by AhmarZaidi** [comment]
Hey Team,

Created a PR for this issue: https://github.com/WordPress/performance/pull/1606

**Comment by felixarntz** [comment]
Is this something we want to encourage? By providing a UI control, we send a signal that this is one of the encouraged ways to configure the plugin, and I wonder whether that's justifiable.

WordPress Core always keeps the original image, even when it's not used as the `full` size, and I'm not sure we want to break with this pattern. One of the reasons is that many sites need those full-resolution images, e.g. photography sites may want to link to them.

More importantly though, why should a Core feature plugin like this provide an option for something that Core doesn't provide an option for? In other words, the decision whether to keep the original image is just as relevant for Core as it is for this plugin, so this plugin doesn't feel like the right place to add an option for this.

@JosVelasco I wonder if there's already a filter in WordPress Core to modify the behavior. If not, we may want to introduce one. That would make more sense to me than implementing it in this plugin specifically (which would mean that Core would remain unaffected, leading to inconsistent behavior).

@adamsilverstein @westonruter Curious what you think about this.

**Comment by westonruter** [comment]
I also doubt whether we should facilitate deleting the original file.

**Comment by JosVelasco** [comment]
At some point, we are moving from a decisions-not-options paradigm to a more options one; at least, that is what I see with the Site Editor and its more advanced options, like the fonts manager.
The filter sounds great, tho. I still think most users won’t touch it.

**Comment by adamsilverstein** [comment]
> At some point, we are moving from a decisions-not-options paradigm to a more options one

It is fine to add an option in a plugin, but I also question the usefulness/advisability of this feature. 

> I also doubt whether we should facilitate deleting the original file.

I agree. The original image is considered user data and for that reason we should probably preserve it. If the user installs a new theme with additional image sizes, they may want to generate those sizes for existing uploads. Without the original upload this is not possible. Even if we kept a modern format copy of the original, we wouldn't want to use that as the new source because compression artifacts would become amplified.

> To save disk space, add an option to the settings to delete the original JPEG / PNG.

If users generate AVIF or WebP instead of JPEG sub sizes we are **already** saving them significant storage space. Removing the original upload would save additional space, however is that really an issue for users? 

For users that really want to delete their original uploads, this is already achievable using existing hooks, or using a plugin purpose built for this like https://wordpress.org/plugins/delete-original-image/

I would suggest we close this ticket after some time for additional discussion.

**Comment by adamsilverstein** [comment]
Closing this as we decided we don't want to make this change here.

**Comment by banago** [comment]
> If users generate AVIF or WebP instead of JPEG sub sizes we are already saving them significant storage space. Removing the original upload would save additional space, however is that really an issue for users?

@adamsilverstein the plugin creates a replica of the original image in AVIF/WebP format which renders all the savings useless in terms of storage sizes. 

While it makes sense to not delete the original uploaded image, it does make sense to skip replicating the original image and only producing the thumbnails.

**Comment by josh-ht** [comment]
Is there any way at all to remove the original images? My use case is best served by only storing the AVIF conversions.
