### ISSUE TITLE
Plugin Proposal: Proposed SEO plugin for Performance Lab program

### ISSUE THREAD

**Issue by phanduynam** [WordPress/performance#1568]
Currently most of the third party SEO plugins like Rankmath, Yoast, All in One SEO cause very slow performance issue for the website. I suggest to create a similar SEO plugin https://wordpress.org/plugins/autodescription/ for better performance.

**Comment by swissspidy** [comment]
Hi there and thanks for your suggestion!

The goal of Performance Lab is to test new performance-related solutions before they can be merged into WordPress core. It is not about creating performant alternatives for every kind of plugin out there. We much rather _collaborate_ with existing plugins and share information and documentation about best practices rather than _compete_ with such companies.
And if you feel like https://wordpress.org/plugins/autodescription/ is already fast, why not use that if you‘re happy with it? :-)

Again, thanks fot the proposal though!

**Comment by joemcgill** [comment]
I agree with @swissspidy's comment above, but would add that WordPress Core itself provides some common framework for providing functionality that can be used and extended by all SEO plugins for creating sitemaps. If it can be determined that core could improve the APIs we provide that are common to all of these plugins, then the development of those APIs could potentially be tracked in this repo in the future.
