### ISSUE TITLE
Defer additional mime type generation to an async routine

### ISSUE THREAD

**Issue by mitogh** [WordPress/performance#159]
## Feature Description

Due an image would contain more than 1 mime type available, and because any mime type that's not the primary one won't be used directly but mostly as a fallback in specific cases like email delivery and such where the primary format is not used, it would make sense to defer this work into an async routine. 

Most of this work can be leveraged to an existing REST API endpoint.

- `POST` - `/wp/v2/media/{IMAGE_ID}/post-process?action=create-image-subsizes`

By calling at this endpoint with the specified attachment ID we can trigger the regeneration of the missing subsizes for a newly updated image and hook there to trigger the creation of all additional mime types besides the primary one (already created by WordPress when the image is uploaded).

### Benefits

The main benefit with this advantage is the fact that images would keep uploading as currently happens (when only 1 mime type is available), and avoid the risk to consume additional resources and preventing failures when uploading new images into the media library. 

The request to process an image would take as much as currently does due this additional image won't be uploaded during the execution of the same script.

### Drawbacks

This approach requires the REST API enabled, some WordPress installations disable the endpoints, and when this scenario is present a different alternative should be considered. (Maybe `wp-ajax` or forced to use everything in the same request).

This approach requires storing the ID of the images creating a queue of images to be processed in order to make sure all images are processed even if a tab is closed or reopened. This process as well can be considered not critical and defer the regeneration of the secondary image as soon as a request would allow performing this job, while the admin editor is open this job can be triggered using the `Heartbeat API` to keep processing the Queue and for FE scenarios WP cron can be used to process the queue. 

---

### Related issues:

- #142

**Comment by adamsilverstein** [comment]
Thanks for opening this @mitogh, I will look into the best approach for async generation. 

> This approach requires the REST API enabled, some WordPress installations disable the endpoints, and when this scenario is present a different alternative should be considered. (Maybe wp-ajax or forced to use everything in the same request).

Core also includes a `wp_ajax_media_create_image_subsizes` callback we could use, might be appropriate especially for the media editor context (vs in the Block Editor)

**Comment by felixarntz** [comment]
@mitogh @adamsilverstein WordPress core currently uses an on-demand approach to generate missing sub-sizes via WP AJAX on retry. Per the implementation from #142, that should also work reliably for the additional WebP sub-sizes. I'm not sure I understand what _performance_ benefits or even reliability benefits using the WordPress REST API would bring here.

I agree that using the REST API would certainly be a cleaner approach than WP AJAX, but I don't think building that out is a high priority, especially from a performance perspective it would barely make any difference. Since the JS side of image uploads is quite cumbersome to work with, I don't think the time investment here would be worth the benefits. Of course, if anybody is willing to dive into it, I'd be not at all opposed to the change, but it'll take a lot of time for, again, little benefit.

I think this issue would be better suited as a WP core Trac ticket for the future, rather than an issue on this repository, since it's not related to performance, and it is also irrespective of whether WordPress core supports WebP or not.

**Comment by adamsilverstein** [comment]
> @mitogh @adamsilverstein[](https://teams.googleplex.com/adamjs@google.com) WordPress core currently uses an on-demand approach to generate missing sub-sizes via WP AJAX on retry. Per the implementation from https://github.com/WordPress/performance/issues/142, that should also work reliably for the additional WebP sub-sizes

Note that core already provides a REST API endpoint that will generate missing image sizes: https://github.com/WordPress/wordpress-develop/blob/ecf1d6a158c70dd7f10cc42c4b26ecb0fb22bb59/src/wp-includes/rest-api/endpoints/class-wp-rest-attachments-controller.php#L375-L386 (/post-process-item with `create-image-subsizes` parameter). I expect this endpoint is used by uploads within Gutenberg.

**Comment by mitogh** [comment]
Due we are using the retry mechanism in Core that would handle everything in a single request and pick up where it left we can close this one.
