### ISSUE TITLE
Remove root style.css

### ISSUE THREAD

**Issue by dainemawer** [WordPress/performance#181]
## Feature Description

Historically, theme meta data has been added through an empty `style.css` file placed in the root of the theme. 

With the addition of `theme.json` this seems a little redundant now. Every WP site currently makes a request to the empty `style.css` which is at the very least a server request and a CSS file to parse, even though there is generally no CSS to be found in the file. I feel like this extra server request can be saved and rather handled on the server going forward, or parsed in through `theme.json`. We have all the tools, mechanisms and more to handle this without involving the Frontend at this point.

**Comment by felixarntz** [comment]
@dainemawer Can you clarify this request? Do you mean this plugin should include a module to not load empty `style.css` files from themes?

**Comment by aristath** [comment]
If I understand correctly, this is about deprecating the `style.css` file in block themes - or at least no longer require such a file. The `style.css` headers that define the theme name and other properties can live inside the `theme.json` file (theme name, author, version, textdomain etc).
Making such a change is possible, and would certainly be a good thing. However, it's not something that can easily be done in the context of a plugin... Such a change would require significant changes to the theme.json parser, the `WP_Theme` class, the updater classes in WP-Core and so on.
If this happens it will have to be done directly in WP-Core since it will require changes to core files in functions & methods that are not directly hookable.

**Comment by dainemawer** [comment]
I think @aristath pretty much cleared up what I was getting at. I totally agree that this may be a core change. The MO here would be to simply just save a server request and not load an empty `style.css` just for metadata. This approach is somewhat outdated now.

**Comment by swissspidy** [comment]
This is best suggested on Core Trac as an enhancement. Worth noting though that there's a lot of caching already implemented in `WP_Theme`, so the impact of `style.css` for any theme is really minimal. It is not something that came up as a big issue in profiling so far, as far as I know.

**Comment by swissspidy** [comment]
Closing as per the above
