### ISSUE TITLE
Disable Excess WP Head Requests

### ISSUE THREAD

**Issue by dainemawer** [WordPress/performance#182]
## Feature Description

We came across this a while back at 10up, and have included a file through `functions.php` that helps get rid of some files that users may not want to be loading on page load. We dubbed it `overrides.php` and it can be found [here](https://github.com/10up/wp-scaffold/blob/trunk/themes/10up-theme/includes/overrides.php).

The functionality of this files disables Emoji Support, Generator Tags, RSD Links and Windows Live Writer. 
Where as Im sure most site users may want to keep this kind of support depending on their use case, a lot of theme developers like to remove it, especially on larger, more custom builds. Could be a nice option to add in an "Advanced" area of the plugin.

**Comment by felixarntz** [comment]
While the removal of unnecessary `wp_head` meta tags, scripts, etc. is certainly a common use-case, there are several solutions to achieve this already, and overall this doesn't make for a good fit for the Performance Lab plugin. While I do that on some of my personal sites too, most of that removal is purely for "clean up" rather than a notable performance benefit.

If there is a concrete performance benefit for removing something which is barely useful, then we should rather focus on that concretely, e.g. via a module that just removes that one thing (or makes it more performant).

I will close this for now, but feel free to open a more concrete performance issue related to a `wp_head` item.
