### ISSUE TITLE
Auto-delete head branches after PRs are merged

### ISSUE THREAD

**Issue by mxbclang** [WordPress/performance#209]
Per [discussion in Slack](https://wordpress.slack.com/archives/C02KGN5K076/p1646681493753469), this is an issue to decide if we want to [set branches to auto-delete](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches) when their PRs are merged, or instead rely (as we have been to date) on manually cleaning up branches.

**Comment by tillkruss** [comment]
I did enable this earlier today while cleaning branches (before this was posted). We can revert this if needed.

**Comment by felixarntz** [comment]
This is related to #214 - we need to iterate on the release branching strategy so that auto-deleting branches wouldn't also delete the `release/**` branches (which would happen today when merging back into `trunk`).

**Comment by gagan0123** [comment]
I'd like to add that in case something does not work after the merge, its usually easier to do a diff of branches and see what could be the potential cause without much effort. I'm also in favor of keeping least number of branches so as to avoid any confusion. Could it be possible to simply delete the branches that have been merged **after 1 week** instead of instantly?

**Comment by swissspidy** [comment]
@felixarntz Then you should mark those branches as protected

**Comment by jeffpaul** [comment]
I concur with the enabling of the setting as @tillkruss did, otherwise it will almost certainly lead to many unnecessary branches sitting around.

**Comment by felixarntz** [comment]
I have opened #221 with updated release instructions that support considering `trunk` and any `release/*` branches as protected branches, so that could use your review.

Once that is approved in some capacity, we can move ahead, protect the relevant branches and then enable auto-deletion.

**Comment by felixarntz** [comment]
Now that #214 is completed, we can move this forward by protecting the branches and then enable auto-deletion of branches. However, I just tried accessing the settings and for some reason it looks like our access has been removed again - not sure if that was intentional for some reason or accidental. Can you check please @dd32?

**Comment by dd32** [comment]
> looks like our access has been removed again - not sure if that was intentional for some reason or accidental. Can you check please

Oops, Performance team restored to Admin. Looks like I changed it accidentally when adding someone to the team.

**Comment by felixarntz** [comment]
Thanks @dd32!

Update on the progress here:
* I have now added a branch protection rule for `release/*` that is the same to what we already had for `trunk` (e.g. branch cannot be deleted, 2 approving maintainer reviews required, all status checks on a PR must pass).
* I have re-enabled the setting to delete head branches after PR merges. Due to the above branches being protected, this should still never delete these key branches.

With the above, I think we can consider this issue completed.
