### ISSUE TITLE
Standardize structure for Site Health reports

### ISSUE THREAD

**Issue by mitogh** [WordPress/performance#229]
## Feature Description

Currently, there's no clear definition in how some things are helpful for performance and why others are being measured, setting a standard by answering a set of predetermined questions would help in making sure the metrics are meaningful for the majority of users and not just technical users.

- **Why this measure is being tracked?** Answer this question in a clear way would help to understand the need to pass this test for example:

![2022-03-14_18-11](https://user-images.githubusercontent.com/3921289/158281099-a2644ad3-070d-4f5a-a71a-bf2021eeacd4.png)

The metric above does not indicate why I need to keep WordPress up to date.

- **Why I need to pass that metric?** or **How the metric would help improve my performance?** Example:

![2022-03-14_18-11](https://user-images.githubusercontent.com/3921289/158281099-a2644ad3-070d-4f5a-a71a-bf2021eeacd4.png)

What's the benefit of passing this test or keeping up to date with WordPress as a site owner what are the risk and benefits of going down this route? Is there any tradeoff If I decided not to? 

Avoid technical wording if possible

![2022-03-14_18-26](https://user-images.githubusercontent.com/3921289/158282538-0c3f041a-630f-4cc2-9fda-180f1c7b8956.png)

This example is missing some answers for the questions above, but also includes additional wording that might not be explicit for the vast majority of users.

**Comment by mxbclang** [comment]
Just noting that I'm happy to help with updating language!

**Comment by mitogh** [comment]
Thanks, That would be really helpful @bethanylang

**Comment by dainemawer** [comment]
Yeah agreed @mitogh we could probably use some direction from: https://github.com/GoogleChrome/lighthouse/blob/master/docs/plugins.md#audit-titles

**Comment by eclarke1** [comment]
Just adding this to the Site Health project.

**Comment by mxbclang** [comment]
@mitogh @manuelRod My thoughts on how to better align the language on each of the four Site Health checks that we have so far are below. I tried to answer the questions that Cris noted above as well as align with the "voice" in the core messages. If I thought that the item title (e.g. Autoloaded options) should also be updated, I've noted that, as well. 

I don't feel comfortable updating these myself in the code, so if these look good to you, could one of you submit PR(s) with these changes? Let me know if you have any questions!

## Audit Enqueued Assets

Opened a separate issue for this as it will require some more discussion: #267.

## Autoloaded Options

_Note that this will also need to be updated to add in documentation in #234._

### If acceptable

<img width="818" alt="image" src="https://user-images.githubusercontent.com/12189958/159726575-fb4240a5-630f-4aca-9dee-863e909873f2.png">

**Current title**: Autoloaded options 

**New title**: Autoloaded options are acceptable

**Current description**: The amount of 269 autoloaded options (size: 121 KB) in options table is acceptable.

**New description**: Autoloaded options are configuration settings for plugins and themes that are automatically loaded with every page load in WordPress. Having too many autoloaded options can slow down your site. Your site has [number] autoloaded options (size: [size]) in the options table, which is acceptable.

### If not acceptable

<img width="825" alt="image" src="https://user-images.githubusercontent.com/12189958/159726520-407a3661-bdf7-4da8-8633-6e81e4bd1672.png">

**Current title**: Autoloaded options

**New title**: Autoloaded options could affect performance

**Current description**: Your website uses [amount] autoloaded options (size: [size]). Try to reduce the number of autoloaded options or performance will be affected.

**New description**: Autoloaded options are configuration settings for plugins and themes that are automatically loaded with every page load in WordPress. Your site has [number] autoloaded options (size: [size]) in the options table, which could cause your site to be slow. You can reduce the number of autoloaded options by cleaning up your site's options table.

## WebP Support

<img width="820" alt="image" src="https://user-images.githubusercontent.com/12189958/159722773-f28ab955-d702-461e-bb2b-299b35fda00d.png">

### Not enabled

**Current description**: WebP image format is used by WordPress to improve the performance of your site by generating smaller images than it usually could with the JPEG format. This means your pages will load faster and consume less bandwidth.

Please contact your host and ask them to add WebP support.

**New description**: The WebP image format produces images that are usually smaller in size than JPEG images, which can reduce page load time and consume less bandwidth. WebP support can only be enabled by your hosting provider, so contact them for more information.

### Enabled

<img width="828" alt="image" src="https://user-images.githubusercontent.com/12189958/159726699-4939dea1-c20e-44d8-8038-139e49154f17.png">

**Current description**: WebP image format is used by WordPress to improve the performance of your site by generating smaller images than it usually could with the JPEG format. This means your pages will load faster and consume less bandwidth.

**New description**: The WebP image format produces images that are usually smaller in size than JPEG images, which can reduce page load time and consume less bandwidth. 

## Persistent Object Cache Health Check

<img width="811" alt="image" src="https://user-images.githubusercontent.com/12189958/159723005-b6bdb947-615c-45ec-b24b-4db6650797cb.png">

### Needed

<img width="819" alt="image" src="https://user-images.githubusercontent.com/12189958/159726817-38bb2af4-1c46-4ea4-975c-75ac137a7e52.png">

**Current description**: WordPress performs at its best when a persistent object cache is used. A persistent object cache helps to reduce load on your SQL server significantly and allows WordPress to retrieve your site's content and settings much faster.

Speak to your web host about what persistent object caches are available and how to enable them. Your host appears to support the following object caching services: [caching service(s)].

[Learn more about persistent object caching. (opens in a new tab)](https://wordpress.org/support/article/optimization/#object-caching)

**New description**: A persistent object cache makes your site's database more efficient, resulting in faster load times because WordPress can retrieve your site's content and settings much more quickly. Your hosting provider can tell you if persistent objects caches are able to be enabled on your site. Your host appears to support the following object caching services: [caching service(s)].

[Learn more about persistent object caching. (opens in a new tab)](https://wordpress.org/support/article/optimization/#object-caching)

### Not needed

<img width="835" alt="image" src="https://user-images.githubusercontent.com/12189958/159734871-11b6c063-d0c9-4710-b3d9-d07d6aa1220c.png">

**Current description**: WordPress performs at its best when a persistent object cache is used. A persistent object cache helps to reduce load on your SQL server significantly and allows WordPress to retrieve your site's content and settings much faster.

[Learn more about persistent object caching. (opens in a new tab)](https://wordpress.org/support/article/optimization/#object-caching)

**New description**: WordPress performs at its best when a persistent object cache is used. A persistent object cache helps to reduce load on your SQL server significantly and allows WordPress to retrieve your site's content and settings much faster. Your site would not currently benefit from a persistent object cache.

[Learn more about persistent object caching. (opens in a new tab)](https://wordpress.org/support/article/optimization/#object-caching)

**Comment by mitogh** [comment]
> I don't feel comfortable updating these myself in the code, so if these look good to you, could one of you submit PR(s) with these changes? Let me know if you have any questions!

Sure @bethanylang let's add it as a `Good First issue` and `Needs Dev` once we agreed on the wording, to see a contributor want's to jump on this one, otherwise I can take over this one in case none wants to address this issue. 

For the most part, everything looks great, I have some feedback on some items so let me know what do you think.

> The WebP image format produces images that are smaller in size than JPEG images, which can reduce page load time and consume less bandwidth. WebP support can only be enabled by your hosting provider, so contact them for more information.

Just to be safe this is true for most cases but not all cases, so maybe we can update to: 

_The WebP image format produces images that are usually smaller in size than JPEG images_

Besides that everything looks great, thanks @bethanylang

**Comment by mxbclang** [comment]
@mitogh That change makes sense, thank you! I've updated.

Adding those labels now and we'll see if we have any takers.  :)

**Comment by mitogh** [comment]
Fantastic thanks @bethanylang

**Comment by felixarntz** [comment]
@bethanylang @mitogh Since it's a bit easier to review the copy with in-line comments rather than in GitHub issue comments, I suggest we proceed with a PR already and ask for feedback on the exact wording _on the PR_. That allows reviewers to put inline comments and we can iterate directly in there. I see you already opened #269 🙌
