### ISSUE TITLE
Set up code owners

### ISSUE THREAD

**Issue by tillkruss** [WordPress/performance#23]
As per @felixarntz suggestion in #2, should we set up a [`CODEOWNERS`](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) file to automatically assign issues and PRs?

It would help reduce the noise.

**Comment by JustinyAhin** [comment]
@tillkruss it would definitely make sense to set up that to automatically assign PR reviewers. Not sure why/if we should do the same for issues though.

**Comment by JustinyAhin** [comment]
And from the GitHub documentation you shared, it is only for PRs.

**Comment by felixarntz** [comment]
I just realized that the [current `CODEOWNERS` file](https://github.com/WordPress/performance/blob/c1a077075a88a4d13203833e6825f1f715599633/.github/CODEOWNERS) is not fully accurate:
* It still contains `modules/webp-uploads` but following #46 all modules will be in focus area-specific directories, so this needs to be changed to `modules/images` - which actually makes the `CODEOWNERS` file maintenance a lot simpler in the long run.
* Based on the above, I suggest we now already add the code owners for all 5 focus areas, even if there's no code yet. We couldn't do this in the way it currently is since we don't know in advance which modules will exist, but we _do_ already know the focus areas, so we can add the focus POCs as code owners, for `modules/images`, `modules/javascript`, `modules/site-health`, `modules/measurement`, and `modules/object-caching`.

I suggest we open a follow-up PR for this issue to fix/expand this.

cc @JustinyAhin @tillkruss
