### ISSUE TITLE
Provide polyfill to serve JPEG or PNG if a page contains WebP images

### ISSUE THREAD

**Issue by eugene-manuilov** [WordPress/performance#341]
## Feature Description

In order to provide support for webp on older browser we need to load webp-hero polyfill on pages that have webp images. The polyfill needs to be loaded only if webp isn't supported by the browser.

https://github.com/chase-moskal/webp-hero

**Comment by eugene-manuilov** [comment]
@adamsilverstein @felixarntz after looking at the webp-hero library I found that the polyfill has very limited functionality. It certainly helps to load webp images when they aren't supported by the browser, but images loaded dynamically (pulled from the server using AJAX requests or added by js script) won't be polyfilled automatically.

This happens because to start polyfilling we need to call the `polyfillDocument()` method of the `WebpMachine` instance and if we want to update images loaded dynamically we need to call this method again. Of course, we don't know when images are updated on the page and call the `polyfillDocument()` method only on initial page load. So theme developers will need to call that method on their own if they want the polyfill to work correctly for their dynamic pages.

Another problem is that the polyfill doesn't respect the `loading` attribute of polyfilled images. If some images on the page are supposed to be loaded lazily, the library ignores it and loads all images as soon as we call the `polyfillDocument()` method.

Finally, the polyfill library doesn't support responsive images and picture element. So any alternative sizes or sources defined in the `srcset` attribute or in the picture element will be ignored and only images from the `src` attribute will be used.

These are the current limitations of the `webp-hero` library. Of course, with all this problems the library still does its job for the initial images on the page when webp is not supported by the browser.

Let me know what you think about it.

**Comment by felixarntz** [comment]
@eugene-manuilov 
> after looking at the webp-hero library I found that the polyfill has very limited functionality. It certainly helps to load webp images when they aren't supported by the browser, but images loaded dynamically (pulled from the server using AJAX requests or added by js script) won't be polyfilled automatically.
> [...]
> Another problem is that the polyfill doesn't respect the loading attribute of polyfilled images.

I think the part of not supporting AJAX-loaded pictures is not super critical since it nothing WordPress themes typically do, but the aspect of breaking/ignoring `loading="lazy"` is a no-go IMO. Even the AJAX-loaded pictures it would be good to support them though.

I think a solution that somehow relies on `HTMLImageElement.onload` and/or [`HTMLImageElement.complete`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/complete) would make sense. We could e.g. use a delegate listener on the `body` element so that it also works for images that are injected into the DOM after initial page load.

> Finally, the polyfill library doesn't support responsive images and picture element. So any alternative sizes or sources defined in the `srcset` attribute or in the picture element will be ignored and only images from the `src` attribute will be used.

That's also not great. We need to at least make sure the image file that is actually being used by the browser (which may not be the one in `src`) is made available in JPEG.

With these concerns, I'm leaning against using https://github.com/chase-moskal/webp-hero. Other than the above drawbacks, it's also not extremely popular, and there's always room for concerns when including external libraries in WordPress core.

How complex would it be to implement our own JS polyfill? At its foundation, it would probably need to function something like I mentioned above, so that it can also affect images that are not in the DOM right away. For the implementation for _how_ to serve JPEG images to browsers for images that are WebP, we have a few alternate options:
1. Generate JPEG images on the fly in the browser, similar to https://github.com/chase-moskal/webp-hero
2. Change every image's file extension from `.webp` to `.jpeg`, assuming WordPress generates both of them. Then, if the JPEG image request fails with a 404, change it back to WebP, since in that case the site owner explicitly decided not to support JPEG
3. Get some allowlist of which images are available in JPEG and only change those from `.webp` to `.jpeg`. Then we don't have to attempt JPEG requests and run into 404s. The flipside would be that we would need some way to get the availability right away (probably in e.g. a REST request, since it shouldn't be computed on every page load since very few sites will need it)

I think approach 2. or 3. make overall more sense than 1., and they would also be easier to implement ourselves. They may very well even be faster (especially 3.), since we would rely on existing images instead of generating them on the fly. Of course this won't work for sites that decide to not generate JPEG versions, but I think then it would be okay since the site owner consciously decided against it.

What do you think? Maybe we can work on a small design doc / implementation proposal for this and assess the amount of work? If we can complete this in the next 4-6 weeks, we would still be well set up to get it ready for WordPress 6.1.

**Comment by eugene-manuilov** [comment]
@felixarntz 

> How complex would it be to implement our own JS polyfill? At its foundation, it would probably need to function something like I mentioned above, so that it can also affect images that are not in the DOM right away.

I think what we need to use is the MutationObserver that allows us to monitor DOM tree and perform different actions when a new node is added or an existing one is removed. It will allow us to add event listeners for the `error` event to already existing images and images that added dynamically to the page. The error handler will let us detect "broken" images after they are actually loaded which will work nicely with the `loading="lazy"` attribute.

<details>
<summary>Here is an example of how it can work:</summary>

```html
<html>
	<head>
		<script>
			var observrer = new MutationObserver(function(mutationList) {
				for (var i in mutationList) {
					var mutation = mutationList[i];

					// Add onerror listeners to all new images.
					for (var j in mutation.addedNodes) {
						var node = mutation.addedNodes[j];
						if (node.nodeName !== "IMG") {
							continue;
						}

						if (node.src.match(/\.webp$/i)) {
							node.addEventListener('error', onErrorHandler);
						}

						console.info("Added a new image with " + node.src + " source.");
					}

					// Remove onerror listeners from all removed images.
					for (var j in mutation.removedNodes) {
						var node = mutation.removedNodes[j];
						if (node.nodeName !== "IMG") {
							continue;
						}

						if (node.src.match(/\.webp$/i)) {
							node.removeEventListener('error', onErrorHandler);
						}

						console.info("Removed the image with " + node.src + " source.");
					}
				}
			});

			observrer.observe(document.documentElement, {
				subtree: true,
				childList: true,
			});

			function onErrorHandler() {
				console.log(this); // this - an image instance.
				// 1. read image data 
				// 2. convert to jpeg
				// 3. write image data back to the img tag using data URI?
			}
		</script>
	</head>
	<body>
		<div>
			<p>Images loaded from the beginning:</p>
			<picture>
				<img src="https://placehold.co/30x30">
			</picture>
			<img src="https://placehold.co/50x50">
		</div>
		<hr>
		<button id="btn">add image</button>
		<div id="images">
			<p>Images loaded dynamically:</p>
		</div>
		<script>
			var counter = 0;
			var images = document.getElementById('images');
			document.getElementById('btn').addEventListener('click', function() {
				var img = document.createElement('img');
				img.src = 'https://placehold.co/60x' + (40 + counter++);
				img.onclick = function() {
					images.removeChild(img);
				};

				images.appendChild(img);
			});
		</script>
	</body>
</html>
```

</details>

> For the implementation for how to serve JPEG images to browsers for images that are WebP, we have a few alternate options:

I think we can leverage the approach used by the `webp-hero` library to convert images on the fly using the `libwebp` library but instead of using canvas, we will use the data URL approach to preserve the original img tag. Or as an alternative to `libwebp` we can probably try to create a WASM application using golang (to [decode webp](https://pkg.go.dev/golang.org/x/image/webp#Decode) and [save as jpeg](https://pkg.go.dev/image/jpeg#Encode)), but it will be supported by less browsers than the `libwebp` approach.

One caveat here is that we will have to suppress the `srcset` attribute values once converted webp image is used to make sure the browser uses the right image from the `src` attribute that will contain the data URL. This shouldn't be a big problem because we will always have the correct image at the beginning because browser will select the right one for the initial viewport. Of course, if a user resizes the window they will keep seeing the same image until refresh the page.

Two other options seem to be less reliable to me.

**Comment by felixarntz** [comment]
@eugene-manuilov 
> I think what we need to use is the MutationObserver that allows us to monitor DOM tree and perform different actions when a new node is added or an existing one is removed. It will allow us to add event listeners for the `error` event to already existing images and images that added dynamically to the page.

The `MutationObserver` approach sounds promising. However I'd prefer if we can find a solution that doesn't require the requests to error until we replace the WebP images with JPEG images. We will already check before loading the shim that WebP is not supported by the browser, so I was thinking more along the lines: Can we replace the WebP images with their JPEG versions right away (i.e. script running first, in the header), before the `img` tags even attempt to load the files, which will fail anyway?

> Two other options seem to be less reliable to me.

Can you clarify why? It seems wasteful and unnecessary to me to use a library that generates JPEG images when WordPress already has JPEG images available anyway.

**Comment by eugene-manuilov** [comment]
@felixarntz 

> > Two other options seem to be less reliable to me.
> 
> Can you clarify why? It seems wasteful and unnecessary to me to use a library that generates JPEG images when WordPress already has JPEG images available anyway.

>> 2. Change every image's file extension from .webp to .jpeg, assuming WordPress generates both of them. Then, if the JPEG image request fails with a 404, change it back to WebP, since in that case the site owner explicitly decided not to support JPEG

This approach is based on the assumption that JPEG versions are also available on the server, but if there are no then "fallback" to webp again which is not supported by the browser thus the user will not see an image at all. Of course, we can say that in this case we can use the `libwep` approach to generate the JPEG version from webp, but in this case why do we need to deal with JPEGs if we eventually have to use the `libwebp` anyway?

>> 3. Get some allowlist of which images are available in JPEG and only change those from .webp to .jpeg. Then we don't have to attempt JPEG requests and run into 404s. The flipside would be that we would need some way to get the availability right away (probably in e.g. a REST request, since it shouldn't be computed on every page load since very few sites will need it)

If we go with an additional REST request to load allowed images, then it will almost most likely mean that some images will finish loading webp versions and display as "broken" in the browser by the time when we receive JPEG alternatives list from the server. Then we will need to update images that have corresponding JPEG versions and hope that there are no other webp images on the page with no JPEG counterparts. If there are such webp images (with no jpegs) then we have to use the `libwep` approach again to make sure they are displayed in the browser somehow.

What I want to say here is that these approaches have edge cases when we need to polyfill webp images. Therefore we will have to have the `libwebp` implementation anyway otherwise we can't consider such implementation as a polyfill if it will work for some images only.

> Can we replace the WebP images with their JPEG versions right away (i.e. script running first, in the header), before the img tags even attempt to load the files, which will fail anyway?

Same here, this approach may work, but it will work only for images that have JPEG versions which is not always true even if the user has selected the option to preserve JPEGs version (for example if the user uploads a webp images directly, or inserts an image into a post that is stored on a different site).

I think that one way or another, we will have to have `libwep` as fallback anyway and if this is inevitable, then maybe it makes sense to make it our first approach and don't rely on others?

**Comment by felixarntz** [comment]
@eugene-manuilov 
> This approach is based on the assumption that JPEG versions are also available on the server, but if there are no then "fallback" to webp again which is not supported by the browser thus the user will not see an image at all. Of course, we can say that in this case we can use the `libwep` approach to generate the JPEG version from webp, but in this case why do we need to deal with JPEGs if we eventually have to use the `libwebp` anyway?

JPEG versions will only not be available on the server if the site owner consciously decides to not use JPEG at all - in which case it is arguably no longer core's problem. There will always be a JPEG version available unless that behavior has been disabled using the filter.

If the site no longer has JPEG versions available for an image, there are other backward compatibility problems than just for the website frontend. For example, any special use-cases outside of the frontend (e.g. email newsletters) that don't support WebP will also break - `libwebp` will not help there.

The default implementation keeps the JPEG images particularly for this reason, for backward compatibility. Using `libwebp` to generate JPEG versions on the fly is therefore wasteful, and it is slower too. And again, it doesn't fully solve the problem even when JPEG versions are not available.

My vote here is to not use `libwebp` at all and only use the JPEG images available because that is precisely why the default behavior is to keep them. Site owners can decide to only keep WebP images, then making a decision in favor of storage space but against backward compatibility.

> If we go with an additional REST request to load allowed images, then it will almost most likely mean that some images will finish loading webp versions and display as "broken" in the browser by the time when we receive JPEG alternatives list from the server.

Fair point. I wonder, would it be possible to somehow manipulate the browser behavior to block loading any images until this logic has executed? Maybe not, but worth a thought.

> What I want to say here is that these approaches have edge cases when we need to polyfill webp images. Therefore we will have to have the `libwebp` implementation anyway otherwise we can't consider such implementation as a polyfill if it will work for some images only.

See my point above. If the site owner makes a conscious decision against backward compatibility (by disabling the JPEG creation), then that's no longer on us (or on core). Users are free to make that decision - the default our implementation provides favors backward compatibility.

**Comment by eugene-manuilov** [comment]
@felixarntz 

> My vote here is to not use `libwebp` at all and only use the JPEG images available because that is precisely why the default behavior is to keep them. Site owners can decide to only keep WebP images, then making a decision in favor of storage space but against backward compatibility.

I am okay with this, but in this case we can't call it polyfill because it is a fallback mechanic, right? In other words, webp images  will fallback to jpegs if they exist, otherwise it's not core's problem 🤷 .

> Fair point. I wonder, would it be possible to somehow manipulate the browser behavior to block loading any images until this logic has executed? Maybe not, but worth a thought.

In theory we can rename `src` and `srcset` attributes to something like `webp-src` and `webp-srcset` in the mutation observer callback. It won't prevent requests to webp images, but at least those requests will be canceled. Anyway, in my opinion UX will become worse if we block images loading until the REST request is finished.

**Comment by felixarntz** [comment]
@eugene-manuilov Fair point, this is probably less of a polyfill then, but rather a fallback mechanism to use existing JPEG images instead of WebP images. It's going to be more efficient than a true polyfill though since we'll rely on the existing resources rather than on-the-fly generating JPEG. :)

> In theory we can rename `src` and `srcset` attributes to something like `webp-src` and `webp-srcset` in the mutation observer callback. It won't prevent requests to webp images, but at least those requests will be canceled. Anyway, in my opinion UX will become worse if we block images loading until the REST request is finished.

Sounds good. Let's go with the approach to just attempt the request then.

**Comment by eugene-manuilov** [comment]
@felixarntz, I have created a PoC #360 that implements your ideas from 2 and 3. Do you mind looking at it? cc @adamsilverstein

**Comment by eugene-manuilov** [comment]
@felixarntz, I assigned this ticket to you. We have multiple approvals for my PR. Let me know if you think we need to do more for it.

**Comment by adamsilverstein** [comment]
Sharing some [screenshots](https://email.browserstack.com/c/eJyFkc2u3CAMhZ8m2WUUDOFnkUWldhZVVVVq98iAk3BnEkaBNK9fppqr7m4lFubwyeYc04rxbik_xmcxH1t7ZNptDKMAkKyHNoyDG4Jq6S951Jdv8TfZn34n2vKSSrZfk7PXuMW8ULBMDqoXCpS2MGkAbkznvDadIM07lA47dL3zignwUrZxlOCF1kTOMQlWanAAJDSbjNGMgRShEf2ON-pOct1bcrk7037rhsmJoKQMutukm_Pl-cN2Gb3UBgPoOoQbDh4DEgdinHHROza193Ep5ZEb_qmBaz3neV7cns7qPBf0t4tPa5XzP4v1xqYJg0FUHIJXPVdGOmeCkdxITT3vOWmpcGj4NZM_dmr457If1IA8ymo9rg-M81bVHxiD_Z5KnKLHEtP2jqSt0FYq8WHCL3qlEI-1wl-etl9iTsfu6V187azQ-rhjof8vr93HGtb6lmvgc0rznZ5RtAtm6wuOv6qdtnzc4g_G2sdK) testing latest PR on Browserstack.

**Comment by feastdesignco** [comment]
As you're adding a filter to disable the automatic webp image generation, please also make the same filter disable the javascript snippet being forced out with this update.

**Comment by felixarntz** [comment]
@feastdesignco This is already the case. If generation or usage of WebP is disabled via one of the two filters, the JS snippet will also not included.
