### ISSUE TITLE
Run PHP unit tests in different versions of PHP

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/performance#399]
## Feature Description

Run PHP unit tests in different versions of PHP in CI.

**Comment by mxbclang** [comment]
Tagging in @felixarntz for further discussion.

**Comment by merkys7** [comment]
We could make Github workflow to test using multiple PHP versions, like the following example: https://github.com/WordPress/rollback-update-failure/blob/main/.github/workflows/wp-phpunit.yml

If that's the case, could I assign this issue to myself?

**Comment by mxbclang** [comment]
@merkys7 I'd like to get @felixarntz's input on this one before we proceed, and he's out of the office for the next few weeks. Stand by.  :)

**Comment by mukeshpanchal27** [comment]
We should set a similar Github workflow that we have for `WordPress/wordpress-develop` https://github.com/WordPress/wordpress-develop/blob/trunk/.github/workflows/phpunit-tests.yml because we have to add our module code/tests on WordPress core so we face some issues when we move our changes here to the core.

**Comment by felixarntz** [comment]
@merkys7 @mukeshpanchal27 @bethanylang I definitely support expanding our GitHub workflow to test using additional PHP versions. However I have some specific feedback:
* We should not test for every supported PHP version as that would take way too long and not really help that much. I would instead choose 3 very different PHP versions and limit testing to those, for example the latest (for now 8.1), the oldest supported (for now 5.6) and something in between (for now e.g. 7.4).
* We should expand and follow the setup in our existing GitHub action rather than creating something from scratch, most importantly we should keep using [`@wordpress/env`](https://www.npmjs.com/package/@wordpress/env) which ensures we maintain our very easy-to-configure setup and don't have to manually maintain a Docker configuration etc.
* Looking at the `@wordpress/env` documentation linked above, it looks like we can set a `WP_ENV_PHP_VERSION` environment variable to force the PHP version to a specific version. So I think we can modify our existing https://github.com/WordPress/performance/blob/trunk/.github/workflows/php-test.yml to include a matrix of PHP versions and then use the above environment variable to set up `@wordpress/env` correctly.

Let me know your thoughts.

**Comment by mukeshpanchal27** [comment]
@felixarntz Sorry for the delay. I agree with you. I will explore that document.

**Comment by mukeshpanchal27** [comment]
@felixarntz I have submitted PR for this issue but different PHP version is not support when we set custom `phpVersion` config value. Check https://github.com/WordPress/gutenberg/issues/29323 for more information.
