### ISSUE TITLE
Add JavaScript coding standard workflow

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/performance#459]
## Bug Description
We should add a JavaScript coding standard because we have now JavaScript in the plugin. I got some JavaScript CS error when I use https://github.com/WordPress/performance/blob/trunk/modules/images/webp-uploads/fallback.js for the WebP core patch.

**Comment by mxbclang** [comment]
Thanks @mukeshpanchal27! Assigning this one to @felixarntz to take a look when he returns.

**Comment by felixarntz** [comment]
@mukeshpanchal27 We already have a JS lint workflow in the plugin. So what we may need to do is adjust that configuration to also cover JS code in that JS file.

**Comment by erikyo** [comment]
@felixarntz why not an additional step using wp-scripts/webpack in order to minify / babel etc? 

if needed I have a ready-made webpack configuration that compiles files in the same folder as the sources so in that way each module will got its own dist folder, I guess that's what's needed in this case is it?

**Comment by felixarntz** [comment]
@erikyo I think that would make sense too now that we have our first production JS file (for the WebP shim). However I think since that is a bit more effort, let's do it in a separate issue and focus this one on just the coding standards validation.

Would you mind creating an issue to implement a wp-scripts based build workflow for production JS files (specifically the WebP shim one for now)?

**Comment by erikyo** [comment]
No i wouldn't mind indeed I am very pleased to do it! I also already have a resolution if you are interested, and to the issue I can attach a PR. 

Anyway doing as you suggest (just for fallback/webp) would basically be and hardcoded configuration... I think we can configure webpack to output directly in the same folder as the source file (inside a "dist/" folder) would make it easier to maintain js script in the future.

**Comment by felixarntz** [comment]
@erikyo Perfect, that sounds great to me 👍

**Comment by swissspidy** [comment]
Closing since there is already such a workflow and #226 exists for bundling
