### ISSUE TITLE
Module Slugs Naming Proposal

### ISSUE THREAD

**Issue by manuelRod** [WordPress/performance#46]
As the number of modules is gonna grow, having just /modules/{module-slug} can lead to difficulties when trying to find one.

Maybe a different approach would help us in the future to easily identify, to which focus area they belong to, for instance:
/modules/{focus}/{module-slug} 
/modules/{focus}-{module-slug}

**Comment by mehigh** [comment]
+1 for a flat structure like /modules/{focus}-{module-slug}

**Comment by ThierryA** [comment]
Generally agree with organizing modules by focus area, I would personally prefer `/modules/{focus}/{module-slug}` as `/modules/{focus}-{module-slug}` by not be obvious to everyone, having folders for focus area makes it more obvious that modules are "grouped".

**Comment by JustinyAhin** [comment]
I agree on having a` /modules/{focus}/{module-slug}` structure for more readability.

**Comment by adamsilverstein** [comment]
makes sense, good suggestion @manuelRod!

**Comment by felixarntz** [comment]
I'm in favor of the nested structure `/modules/{focus}/{module-slug}` as well.

However, note that this will require code changes (e.g. module parsing) and documentation changes, so we need a PR. It would also mean that modules should no longer need to specify the focus in the module header, since it would already be defined by the folder name.

Let's implement the changes to make it work, but we should then only start using that new approach once an eventual PR is merged. In other words, modules added now should still rely on the flat structure without any mention of the "focus" because that's how our code and documentation work now. The PR for this one would then need to migrate any existing modules to the new structure, and after merge all new modules would need to follow that.

**Comment by ThierryA** [comment]
I would be in favor of doing it rather sooner than later to avoid having more modules needing to migrate.

**Comment by adamsilverstein** [comment]
👍🏼  I will create a PR to update the webp-uploads module and adjust our docs to reflect the new naming convention.

**Comment by felixarntz** [comment]
@adamsilverstein Make sure to also updated the way the modules are parsed and loaded, so that the plugin continues to work, e.g.:
* https://github.com/WordPress/performance/blob/trunk/load.php#L101
* https://github.com/WordPress/performance/blob/trunk/admin/load.php#L194

We may need to change the data in the option then so that it stores an array of strings, where each string is the focus slug and module slug separated by a slash, e.g. `images/webp-uploads`.

**Comment by adamsilverstein** [comment]
Question: should we also change the test file structure to move tests into focus sub-folders? eg change `/tests/modules/{module-slug}` to `/tests/modules/{focus}/{module-slug}`

**Comment by felixarntz** [comment]
@adamsilverstein Yes, I think that change should be made everywhere, for consistency. That way we can furthermore always rely on the same full `{focus}/{module}` naming pattern.

**Comment by felixarntz** [comment]
Fixed via #58

**Comment by JustinyAhin** [comment]
@felixarntz I've noticed that you added this issue to the initial release milestone https://github.com/WordPress/performance/milestone/1.

I think we'll only include PRs in the milestones, right? And #58 is already there. Is it okay to remove the issue?

**Comment by felixarntz** [comment]
@JustinyAhin Good catch, yeah the issues don't need milestones - although I don't think it causes any harm since the changelog script for example only considers PRs anyway. I've removed it though.
