### ISSUE TITLE
Add width and height attributes for images added from URL

### ISSUE THREAD

**Issue by adamsilverstein** [WordPress/performance#49]
When images are inserted from a URL in the block editor, the resulting HTML should include the image width and height in order to avoid layout shift. Currently it does not.

See https://github.com/WordPress/gutenberg/issues/6652

Fix might need to be in Gutenberg, adding this ticket here since it can impact image performance.

**Comment by westonruter** [comment]
Seems like this would be straightforward to add in Gutenberg when a remote image is added. Once the image is loaded, the width/height can then be persisted as attributes.

Nevertheless, what if the author is linking to an image without consistent width/height? For example, they could be linking to https://source.unsplash.com/random so that a random image with random dimensions are used. If the dimensions were obtained and stored, then this would break. One may say this authors shouldn't be doing this, but alas, it's something users may indeed do (and have a need to do so).

**Comment by joemcgill** [comment]
This is not totally fixed, but I don't think we have any follow-up to do that needs tracking here. WordPress adds h/w values to images via `wp_img_tag_add_width_and_height_attr()` which runs in `wp_filter_content_tags()`. There are still some edge cases, like images not hosted on the site, which would benefit from adding these via the block markup itself, but I'm unsure how high a priority this should be.

Closing for now as no additional work is planned.

**Comment by westonruter** [comment]
Also closely related to https://github.com/WordPress/performance/issues/10
