### ISSUE TITLE
Create object cache modules

### ISSUE THREAD

**Issue by tillkruss** [WordPress/performance#5]
Similar to #4.

**Comment by felixarntz** [comment]
@tillkruss Instead of creating a single object cache module, I wonder whether it would be better to create modules per project. #4 is about creating a module for WebP, which is a project of the image focus, it's not a module for the overall image focus.

There may be projects in the object cache focus that only make sense to be implemented together, so combining them in such a case makes sense, but overall modules should be for individual projects so that those projects (i.e. performance features or enhancements) can be enabled and tested individually, rather than saying "I want all experimental object caching enhancements no matter what".

**Comment by tillkruss** [comment]
@felixarntz: Sure thing!

**Comment by eclarke1** [comment]
@tillkruss actually I removed the 'Needs Dev' label here as assuming you are picking this up? Would be great to move to 'In Progress' once work commences. However, if you're not the one who is picking this up, perhaps we can unassign you and add the 'Needs Dev' label to indicate to the community it needs Dev? WDYT?

**Comment by tillkruss** [comment]
Closing in favor of #35.
