### ISSUE TITLE
Create Background Processing Infrastructure: Create Perflab_Background_Job Class

### ISSUE THREAD

**Issue by jjgrainger** [WordPress/performance#503]
Create a new `Perflab_Background_Job` class to represent a single job and provide methods for accessing it's data.

## Acceptance Criteria

- Create a new `Perflab_Background_Job` class
- The `__construct()` method should accept 1 parameter
    - `$term` - Can either be the Job term ID or term object
- The class should have the following methods
    - `update_data( array $data )` -  This method will update the jobs `job_data` term meta
    - `data()` This method will return an array of the jobs `job_data` term meta.
    - `complete()` - This method will update the following term meta.
        - `job_completed_at` - Set the term meta to the current timestamp
        - `job_status` - Set the term meta to the string completed.
    - `is_complete()` - This method will return a true if the `job_completed_at` meta is set, false if not.

**Comment by ankitrox** [comment]
#### Synopsis

Background job is technically a taxonomy in WordPress. Background job queue is the collection of terms in the `background_job` taxonomy. Background job class is responsible to manage the terms and other metadata related to the background job infrastructure.

Following are the properties and meta description for job class.

| Name | Property / Meta | Data type  | Purpose | Default |
|----------|----------------------|---------------|-------------|-----------|
| id | property | integer | Technically the `term_id` for `background_job` taxonomy. Holds the job ID of the instance | null |
| action | property | string | Stored as term name in `wp_terms` table. This is the custom action string that is called in the background process. This is prefixed so the final action hooked called is `do_action( 'perflab_job_{$action}' )` | null |
| data | property & meta | array array (stored as string in serialised format) | Holds the data related to job in an instance. This is stored in term meta table with meta key as `perflab_job_data`. | null |
| perflab_job_status | meta | string | Stores the job status in term meta. When the job is created, status will be *queued* | queued |
| perflab_job_error | meta | array (stored as string in serialised format) | Store the error information occurred during job execution. | null |
| perflab_job_attempts | meta | integer | Store the number of attempts for the job's execution. By default, maximum 3 attempts will be allowed. | null |
| perflab_job_lock | meta | integer (timestamp) | Store the timestamp (in seconds) at which the job execution has started. Useful for determination of timeout of the script. | null |
| perflab_job_completed_at | meta | integer (timestamp) | Store the timestamp (in seconds) at which the job execution has completed. Useful for cleaning up the jobs from the queue. | null |


#### Job Statuses

There are several job statuses which are getting stored in term meta with meta key `perflab_job_status`. Following are different job statuses.

| Name | meta_value | Description |
|----------|-----------------|-----------------|
| Queued | queued | This status signifies that job has been created, but no operation has been performed. When the job is created in system, it will have `queued` status by default.|
| Partial | partial | Set when the job is ran partially. This means that the next batch needs to be run for this job. |
| Completed | completed | Job is completed and no further action needs to be taken. | 
| Running | running | Job is currently running. This is useful to resume any jobs for some unknown reasons. | 
| Failed | failed | Job is failed due to some error or issue. `perflab_job_error` meta holds more information about same. |

**Comment by jjgrainger** [comment]
Fixed via #507
