### ISSUE TITLE
Consistency in unit tests

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/performance#514]
## Bug Description
We should follow the consistency in the unit tests. Some tests use `@test` annotation and some functions don't use it. Instead, they use `test_*` in the function name. Most of our unit tests use `@test` annotation.

## Steps to reproduce

https://github.com/WordPress/performance/blob/0a9570795dbc602cbc305d2b47b3a5a589f547cd/tests/plugins/webp-uploads/helper-tests.php#L17

**Comment by thelovekesh** [comment]
All the latest test suites are using the `test_` prefix. Therefore, I believe it makes sense to update the test annotation to include this prefix.

**Comment by swissspidy** [comment]
Agreed. `test_` is more in line with core.

**Comment by AhmarZaidi** [comment]
I'd like to work on this issue.

**Comment by westonruter** [comment]
I think we should also revisit the naming convention for test class names and test file names. Currently we have files like `plsr-url-pattern-prefixer-test.php` which contains `PLSR_URL_Pattern_Prefixer_Tests`. The naming of the class in particular is not ideal because when doing autocompletion, it includes the `*_Test` classes too easily:

![image](https://github.com/WordPress/performance/assets/134745/97df32fc-cce3-4a28-afcf-7535220929d0)

I think perhaps all test classes should be prefixed by `Test_` as well instead of being suffixed with `_Test`. This is also more in line with WordPress core. 

Also, the file names often are suffixed by either `-tests.php` _or_ `-test.php`. I think we should change this to _prefix_ all by just `test-`. This will make it more clear when navigating to a file that the test files are to auto-completed when starting to type `helper`, for example.

**Comment by thelovekesh** [comment]
@westonruter The suggested changes make sense, so I have filed https://github.com/WordPress/performance/issues/1245 to address it separately across all plugins.
