### ISSUE TITLE
Investigate unexpected input `Warning` message during release build process

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/performance#561]
## Bug Description

During the release process for version 1.6.0 of the plugin the "New Release" step threw a warning: 

Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, softprops/action-gh-release, actions/checkout

The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

GB action URL: https://github.com/WordPress/performance/actions/runs/3267138575

## Steps to reproduce

1. Run a release build

## Screenshots
<img width="1374" alt="Screenshot 2022-10-18 at 9 56 22 AM" src="https://user-images.githubusercontent.com/10103365/196335338-3f2cb224-4f88-4b38-a937-bbb1ba013aa7.png">

**Comment by mehulkaklotar** [comment]
All actions will be running on Node 16 instead of Node 12 as [GH changelog suggests](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/). so we need to update the `actions/checkout` to v3 or stable tag and `softprops/action-gh-release` to v1 at least in [deploy-dotorg.yml](https://github.com/WordPress/performance/blob/trunk/.github/workflows/deploy-dotorg.yml) workflow.

[php-lint.yml](https://github.com/WordPress/performance/blob/4a2fa03c8e8c56c14123abef9184cfea6fc08164/.github/workflows/php-lint.yml#L46) needs to update set-output command to `echo "name=dir::$(composer config cache-files-dir)" >> $GITHUB_OUTPUT` as per [GH changelog](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
