### ISSUE TITLE
Let's get WordPress.org into the Green Software Foundation.

### ISSUE THREAD

**Issue by OllieJones** [WordPress/performance#579]
There's a foundation called Green Software Foundation. https://greensoftware.foundation/ Let's join it. (The cost is zero for not-for-profit outfits. But it wouldn't be zero for Automattic, of course.)

It doesn't seem to be an effort at [greenwashing ](https://en.wikipedia.org/wiki/Greenwashing)for software companies, but rather seems to be doing serious work. One of their initiatives is figuring out how to time-shift power-intensive operations to take advantage of cheaper-to-generate power. They have other efforts, both for measurement and for mitigation. At least some of these could eventually be useful to Core Performance.

WordPress's global reach would make this worthwhile.

Discussion?  Ideas? Is this just dumb?

**Comment by mxbclang** [comment]
@felixarntz Tagging you in here for your thoughts!

**Comment by felixarntz** [comment]
I think it would be best to raise this with a larger audience. For example, we could talk about it in the performance chat. But eventually this will require a Make post to gain any traction, and most importantly it will require project leadership support to make it happen.

**Comment by OllieJones** [comment]
Of course. I guess "Project leadership" probably means https://ma.tt , correct?

**Comment by YellowlimeNL** [comment]
I would love to see WordPress joining this Foundation, excellent suggestion @OllieJones

**Comment by OllieJones** [comment]
There's a #sustainability effort going on. https://make.wordpress.org/project/2022/11/01/sustainability-channel-what-should-we-do/ This suggestion of mine is in their wheelhouse. Performance folks have plenty to do. What we do improves sustainability, but we don't have to own the foundation stuff here.

**Comment by mrchrisadams** [comment]
hey folks,

I work as the exec director of the Green Web Foundation, and our (small, non profit) organisation was one of the founding members of the Green Software Foundation. You don't need to be a massive corporate to have a voice, there, and I've been the policy working group chair at the Green Software Foundation since it's inception earlier this year.

I can't said I'm not biased, but we've found it a useful place to engage - given the mindshare Wordpress has, I think it would be a good place to have some sustainability related discussions relating to the web, and the ideas applied in the Wordpress community would likely have quite an impact.

Given there's already lots of work gone into creating a standard for understanding the digital footprint of applications with their [Software Carbon Intensity work](https://github.com/Green-Software-Foundation/software_carbon_intensity), I think it would be really a lot of scope for useful collaboration.

I'm happy to answer questions here, but I'm also happy to answer them directly in the Wordpress slack - I'm mrchrisadams there.

**Comment by mxbclang** [comment]
Thanks so much, @mrchrisadams! I think everyone is onboard with this idea, but as @OllieJones noted above, the Performance Team likely isn't the best group to drive this forward. Any decisions on the broader WordPress software need to be made at the core level, and perhaps the new Sustainability Team that's forming can help come up with a proposal to bring to the core team.

For that reason, I'm going to close this issue out for now as there isn't anything active for the Performance Team to do here, but of course we're happy to help however we can!
