### ISSUE TITLE
Feature request: High Performance AJAX

### ISSUE THREAD

**Issue by batonac** [WordPress/performance#586]
## Feature Description

There are some gists out there demonstrating how the highly-utilized admin-ajax.php can be sped up for frontend requests with a few tweaks, disabling certain admin actions/hooks. According to [the original gist](https://gist.github.com/yllus/8181d8670fd296854c1e41078d969cc1), this can "speed up AJAX requests by 50% or more". [Here's an updated fork for WP 6.1](https://gist.github.com/mcaskill/95acb103a5e5a78a7184b38fbacfa66e).

Would these concepts be applicable for the performance team to look implementing a more general-purpose frontend-focused ajax mechanism that provides a drop-in replacement so existing plugins and themes could benefit from these concepts?

**Comment by eclarke1** [comment]
@felixarntz @joemcgill could I kindly ask for your guidance on where this issue should be placed within focus areas please?

**Comment by jordantrizz** [comment]
> [Here's an updated fork for WP 6.1](https://gist.github.com/mcaskill/95acb103a5e5a78a7184b38fbacfa66e).

This is gold; thank you for providing this. I've been tracking admin-ajax.php issues for some plugins that ultimately bring a site offline due to resource spikes.

https://managingwp.io/2022/09/01/wordpress-plugins-utilizing-admin-ajax-php-causing-performance-issues/

**Comment by batonac** [comment]
To be clear, I didn't really do any work on this, I'm just making connections 😀.

But yes, it seems to me that the implications are rather large and should be fairly high priority for the performance team.

**Comment by joemcgill** [comment]
Thanks for the suggestion, @batonac! Improving the performance of AJAX requests aren't on our immediate roadmap, but I think this is a valid issue for us to keep in mind. If anyone is interested in helping to move this forward in the meantime, I'd suggest A/B testing some use cases with and without the suggested approach applied and report back the performance impact.

@eclarke1 this most likely belongs with other server timing focus items as this relates mostly to the PHP backend that front end JS scripts interact with.

**Comment by jordantrizz** [comment]
> If anyone is interested in helping to move this forward in the meantime, I'd suggest A/B testing some use cases with and without the suggested approach applied and report back the performance impact.

Do you have a standardized format and tool to produce the right data? I can take a stab at it.

The A/B testing would be against popular plugins that utilize the admin-ajax.php on front-end requests. One plugin that seems to have this issue is Pixel Your Site https://wordpress.org/plugins/pixelyoursite/

On shared hosting, 5-10 visits within seconds to a front-facing page will result in a massive slowdown and a spike in resources. Caching is not possible as this is data being recorded into the database.

**Comment by johnbillion** [comment]
This topic has been discussed on and off for many years and the consensus is that a non-admin version of an ajax endpoint provides no benefit over using a REST API endpoint. Yes there is some overhead to the REST API which means it's likely not as performant as a bare-bones front end ajax endpoint can be, but effort would be better placed into improving the performance of the REST API rather than adding another entrypoint.

Some links to previous discussions:

* https://core.trac.wordpress.org/ticket/12400
* https://core.trac.wordpress.org/ticket/45022

**Comment by batonac** [comment]
Makes sense, thanks @johnbillion .

**Comment by nickchomey** [comment]
I'm very late here, but this doesn't make any sense. Tons of plugins and themes use AJAX calls, so you're effectively saying "rewrite everything in the REST API". Moreover, from the reasoning provided here and in #12400, admin-ajax.php should just be deprecated altogether. In lieu of such a terrible idea (and keeping with WordPress' extreme commitment to backwards compatibility), a more performant ajax handler should be introduced.
