### ISSUE TITLE
Add option to store original images to library

### ISSUE THREAD

**Issue by rakesh26dgdjggj** [WordPress/performance#610]
## Feature Description

hi, this is regarding performance lab plugin. the plugin converts the images to webp on upload, which is excellent! but it is really a bad option for a image website, because when the user download the images they see webp image instead of jpeg or jpg or png. 

Add an option in the plugin that saves original (jpeg, jpg, png) images as this feature is not in the current version.
Add an option to revert back images to jpeg or jpg when the plugin is uninstalled and or deactivated.
Add an option to allow users to manually control the conversion process. of images.

I have a image website that has over a thousand of images, it took me a month to build it. and this plugin just destroyed everything. Beauce I cant revert back webp images to jpeg version. and my users don't download the webp images they download jpg or jpeg version which is supported in android.

please add the above mention details asa soon as possible.
contact me Rakesh.sites@gmail.com

**Comment by felixarntz** [comment]
@rakesh26dgdjggj The original image is always maintained, and the Performance Lab plugin adds an option under _Settings > Media_, where you can control whether to generate only WebP or both WebP and JPEG.

Regarding the download specifically, unfortunately there is no way to download an image in another MIME type than what is being served in the HTML response. This is a browser limitation that we cannot address from WordPress or a plugin. I agree with you that it is an issue, but unfortunately we are tied to the limitations in the browser behavior.

I am going to close this issue for now since the requested option exists, but please don't hesitate if you have follow-up feedback.
