### ISSUE TITLE
SQLite module: Doesn't work with WP-CLI

### ISSUE THREAD

**Issue by rosswintle** [WordPress/performance#614]
## Bug Description

The SQLite module does not work with various WP-CLI commands such as:

 - `wp db cli` (opens a MySQL cli)
 - `wp db export` (exports a MySQL file)
 - `wp db transient list` (seems to hang and do nothing)

## Steps to reproduce

1. Create a new site
2. Install the performance plugin and enable SQLite
3. Open a terminal/shell and change to the site's directory
4. Run one of the above commands

## Additional Context

 - PHP Version: 7.4.x
 - OS: MacOS 13.0
 - Browser: n/a
 - Plugin Version: 1.8.0

I'm aware that this could be an issue to raise with WP-CLI rather than with the Performance Lab (or wherever the SQLite integration ends up living). But I wanted to log that I had tried this as part of my testing and it had failed to do what it should.

Thanks

**Comment by dotsam** [comment]
For the `db` commands, presumably WP-CLI would need to add some sort of hooks for a DB drop-in to override, as right now it always assumes MySQL for everything.

As to the `transient list` command, this is probably because WP-CLI uses its own `esc_like` function

https://github.com/wp-cli/cache-command/blob/436c71a33eb59c60363b39a5bf6fdf2ad363de47/src/Transient_Command.php#L366-L368 
```
			$where  = $wpdb->prepare(
				'WHERE `option_name` LIKE %s',
				Utils\esc_like( '_transient_' ) . $pattern
```

which bypasses the `esc_like` method of the sqlite child class https://github.com/WordPress/performance/blob/245c9ebae1a45c2da90d9ae0977c9f4ae716ec86/modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-db.php#L100-L102

This util function seems to have been added as a polyfill for the `wpdb` method in https://github.com/wp-cli/wp-cli/pull/4612 which replaced a previous function that (attempted) to use the `wpdb` method when possible https://github.com/wp-cli/db-command/issues/66

**Comment by felixarntz** [comment]
The SQLite module will be removed from Performance Lab in the upcoming release, see #737 for additional context. As such, please report this issue in the [standalone plugin repository](https://github.com/WordPress/sqlite-database-integration) instead.
