### ISSUE TITLE
Disable the `Enable WebP Uploads?` module if server does not support it.

### ISSUE THREAD

**Issue by mitogh** [WordPress/performance#65]
Right now there's no information when adding the plugin if my current server supports `WebP` or not instead of allowing users to enable the module. Instead, disable the module or don't render the module when is not supported, instead, a message can be displayed instead that the module was not activated due `WebP` is not supported on the current server where the images are being tested. 

![2021-12-22_15-34](https://user-images.githubusercontent.com/3921289/147157811-3a2d05ee-2495-4980-b1aa-faf58fd449ee.png)

**Comment by felixarntz** [comment]
@mitogh This would tie into the infrastructure aspect of the overall plugin, and I'm not sure we should disable the entire module in that screen. We could instead show e.g. an admin notice triggered by the module itself if the server doesn't support WebP?

If we decide this should be shown before the module is even active, we would need to define a centralized approach so that a module is able to declare / run certain "requirements" logic even when it is not active - so depending on what we decide here this either becomes a `[Focus] Images` or `Infrastructure` issue.

**Comment by mitogh** [comment]
Thanks @felixarntz 

The main idea is basically to provide feedback to the user in order to allow a user to identify that a module is not active or can't be active because server limitations, instead of allowing users to enable the module even when no real action can happen.

**Comment by mitogh** [comment]
Additionally, would be ideal if we say that the `webp` conversion is not supported prior to WordPress 5.8.0 as the filter `image_editor_output_format` was introduced after WP 5.8.0.

**Comment by felixarntz** [comment]
> Additionally, would be ideal if we say that the `webp` conversion is not supported prior to WordPress 5.8.0 as the filter `image_editor_output_format` was introduced after WP 5.8.0.

That part should be implicitly covered, since the overall plugin will require 5.8.0 as its minimum WP version (we'll always require the latest WordPress versions since the changes target core, so we'll need to build against the latest version for most modules anyway).

**Comment by felixarntz** [comment]
I'm going to close this issue due to the conversation above. Furthermore, while the module is called "WebP Uploads", what it introduces beyond that is a new infrastructure to have multiple MIME type versions available for an uploaded image, which is not only about WebP.

I think the checks we have to not attempt to generate WebP files when the server doesn't support it is sufficient.
