### ISSUE TITLE
Implement admin pointer to indicate to the user they need to activate the new standalone plugins

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#653]
## Feature Description

Follow-up to #652: For sites where the conditions in #652 apply, an admin pointer should also show up to ensure the user sees that they need to do something on the PL settings screen (specifically, install/activate the standalone plugins for the modules that they used to have active).

### Requirements

* TODO.

**Comment by mukeshpanchal27** [comment]
Hello @felixarntz, since we included the admin notice in issue #652, do we still need to incorporate the [Admin pointer](https://github.com/WordPress/performance/blob/0e10d5a0a924bd1d35345587eabb2984814c502d/admin/load.php#L420)?

Please let me know if I've missed anything here. Additionally, the requirements are absent in the issue description. Could you please provide those details? cc. @eclarke1 @joemcgill

**Comment by felixarntz** [comment]
@mukeshpanchal27 See my PR feedback in https://github.com/WordPress/performance/pull/899#discussion_r1424352978, we shouldn't ever add a general admin notice to all of WP Admin.

For bringing attention to the action the user needs to do on our screen, an admin pointer is more suitable, so I'd say we should implement it in this issue as planned.

**Comment by felixarntz** [comment]
Fixed via #910 and #915
