### ISSUE TITLE
Remove the `@` silencing warnings from PL

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/performance#709]
## Bug Description

Followup for #695 

As @joemcgill suggested in [other conversation](https://github.com/WordPress/performance/pull/695#discussion_r1157718478) we have to remove `@` silencing warnings from all files.

cc. @felixarntz

**Comment by felixarntz** [comment]
@mukeshpanchal27 @joemcgill One thing I'd like to highlight here for context is that _all_ of the `@` usages in Performance Lab are there because closely related code in WordPress core uses them. So we need to review these usages individually and decide whether or not they are worth fixing:
* All `@` usages in `perflab_get_modules()` are there because the function was inspired by WordPress core's `get_plugins()`. I am unsure why the `@` usage is there in WordPress core, but we should probably figure that out before we simply remove our own.
* Note that there is a `// phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged` comment in the `Dominant_Color_Image_Editor_Imagick::get_dominant_color()` method, however that seems misplaced there. Maybe something old that was forgotten to be removed?

**Comment by joemcgill** [comment]
Thanks for the context, @felixarntz. I know that WP Core has gone through a lengthy process of identifying and removing error silencing from a bunch of places in the past few years, so it would be interesting to know if these were not updated in `get_plugins()` intentionally, or if they just haven't gotten around to reviewing these yet.

It looks like there are currently [14 instances of `opendir()` across 9 files in core](https://github.com/search?q=repo%3AWordPress%2Fwordpress-develop%20opendir(&type=code) and they inconsistently use error silencing, so it's probably fine for us to remove them given that we're always checking for the existence of the module file in order to load it, so a warning is probably appropriate in that case.

Regardless, I don't see this as I high priority issue for us to address. More of a nice maintenance cleanup.

**Comment by mukeshpanchal27** [comment]
> * All `@` usages in `perflab_get_modules()` are there because the function was inspired by WordPress core's `get_plugins()`. I am unsure why the `@` usage is there in WordPress core, but we should probably figure that out before we simply remove our own.

As we removed the module infrastucture we no longer needs to check for PL plugin codebase as we remove those code now.

> * Note that there is a `// phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged` comment in the `Dominant_Color_Image_Editor_Imagick::get_dominant_color()` method, however that seems misplaced there. Maybe something old that was forgotten to be removed?

@pbearne Could you tell us which error you want to by pass here? As we are set min 7.2 now can we remove that PHPCS comment?
