### ISSUE TITLE
Enhance the health check message when WebP is not supported

### ISSUE THREAD

**Issue by joemcgill** [WordPress/performance#715]
## Feature Description

Currently, if a site enables the site health check for WebP images, but the site's hosting provider does not support WebP, the only feedback we provide is the following message:

> WebP support can only be enabled by your hosting provider, so contact them for more information.

This doesn't give site owners a lot of information to help resolve the issue. Instead, it would be nice to include a link to some documentation that includes minimum requirements to support WebP that could be copy/pasted to hosting support, or could help self-hosting developers figure out why this isn't working.

In [the announcement post](https://make.wordpress.org/core/2021/06/07/wordpress-5-8-adds-webp-support/) for the inclusion of WebP images in WP 5.8, @adamsilverstein included the following:

> WebP support in the media library requires that your web server’s image processing library (WordPress supports both Imagick and LibGD) supports the WebP format. Fortunately these libraries have supported WebP for quite a while so support is widely available. If your web server does not support WebP, you will see an error message when you try to upload a WebP image.

However, this doesn't give any specifics. Is there a canonical reference somewhere that we could point to?

**Comment by the-hercules** [comment]
@joemcgill As from WordPress 5.8 we have fields like  supported file formats in Site Health Section, can we help site owners by letting them check the supported formats. 

`WebP images are not currently supported by your web server's image processing libraries. This functionality is required to serve WebP images and improve website speed. Check your supported file formats under Tools > Site Health > Info > Media Handling > Supported File Formats. 
`

**Comment by joemcgill** [comment]
Thanks for the suggestion @the-hercules. In this case, if we are showing a site owner the message that WebP is not supported, we already know that WebP will not be in the Supported File Formats information. What I think we want to do is lead people to some documentation that describes how to enable WebP support on your server. It's possible that we will need to create this content if it doesn't already exist so we have something to link to.

@adamsilverstein curious if you have thoughts on this?

**Comment by adamsilverstein** [comment]
>  it would be nice to include a link to some documentation that includes minimum requirements to support WebP

I agree it would be good to improve this message and a link could be useful, because its too complex to describe here.  I found this post after we added WebP support that does a relatively decent job of describing WebP support in the WordPress hosting landscape: https://make.wordpress.org/hosting/2022/03/30/wordpress-hosting-and-webp-support/ This was the #2 result when I searched for "webp php web server support", maybe we could ask @javiercasares about updating that post to keep it current? Another idea (maybe for later) would be to create a more evergreen page in the Handbook somewhere that gave a similar overview of modern image format handling in WordPress and covered both WebP and AVIF.

WebP support is complex because it depends on how the server is built (so for example, it isn't strictly tied to the PHP version your server runs). Fortunately, most commonly distributions have support for WebP by default, so its only a very small percentage of WordPress site servers that don't support WebP.  Essentially these are sites where GD or Imagick has been built without WebP support. 

In practice for WordPress users this probably means migrating to a different plan (or maybe even host), because updating the underlying infrastructure can be prohibitively risky for hosts. 

How about expanding the text:

_Ask your host about switching to a plan that supports WebP, or switch to a host with support. [Learn more](https://make.wordpress.org/hosting/2022/03/30/wordpress-hosting-and-webp-support/) about WebP image support for WordPress sites._
