### ISSUE TITLE
Enhancing the Scripts API with a loading strategy

### ISSUE THREAD

**Issue by eclarke1** [WordPress/performance#755]
This [Type] Overview issue is designed to act as an entry point to understanding the work being completed for **Enhancing the Scripts API with a loading strategy**

See [feature proposal](https://make.wordpress.org/core/2022/12/09/enhancing-the-scripts-api-with-a-loading-strategy/) and [Trac ticket](https://core.trac.wordpress.org/ticket/12009)
Feature is currently being developed in [this fork branch](https://github.com/10up/wordpress-develop/tree/feature/enhance-wp-scripts-api-with-a-loading-strategy)

**Comment by adamsilverstein** [comment]
Can this one be closed as well @felixarntz?

**Comment by felixarntz** [comment]
@adamsilverstein I think _almost_. For 6.3, I believe the only part that we still want to do is expand the documentation (cc @10upsimon).

Other than that, for 6.3 we're pretty much done with this. The question is whether we want to continue using this issue for any follow-up effort of _adopting_ the script loading strategy in 6.4 or not. Given we have #786 already, potentially that issue is more suitable for that.

**Comment by joemcgill** [comment]
All the relevant docs have been updated now, so I'm going to close this one out. We can reopen, or create new tickets for anything that is left over.
