### ISSUE TITLE
Errors in Performance Lab Plugin Detected by Plugin Checker

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/performance#787]
## Bug Description
When i check the Performance Lab plugin in [Plugin Checker](https://github.com/10up/plugin-check/) tool it shows errors that we have to fix in upcoming release.

When running the Performance Lab plugin through the [Plugin Checker tool](https://github.com/10up/plugin-check/), we discovered that several errors were flagged. These issues need to be addressed and fixed in the upcoming release.

## Screenshots
<img width="1576" alt="Screenshot 2023-07-20 at 12 04 16 PM" src="https://github.com/WordPress/performance/assets/10103365/30961555-bc5f-47f1-b636-8e07dec31022">

**Comment by mukeshpanchal27** [comment]
cc. @eclarke1 @felixarntz @joemcgill

**Comment by felixarntz** [comment]
Thanks @mukeshpanchal27!

Regarding the hidden files error, we can probably just remove the `.gitkeep` file? Otherwise we could exclude it so that it doesn't make it to .org, but I'd argue we don't even need that file anymore.

For the other errors, they make sense, but there seems to be an issue with our tooling here, since our PHP linting workflow should have caught this long ago?

I just took a closer look, and it looks like the issue is that the `./server-timing` directory is not part of our `phpcs.xml.dist` config, looks like we failed to update that. `phpstan.neon.dist` looks like it's complete though, so we should probably make sure to align the `phpcs.xml.dist` list of directories and files. When we address those issues, we'll also have addresses those violations that the plugin checker found.

**Comment by swissspidy** [comment]
WordPress core itself trusts translations, which is why you don't see `__()` calls being escaped anywhere. Many plugins do the same. We should consider updating the Plugin Checker to either not flag translation calls or at least make them warnings. It really adds a lot of noise for something that is not even considered an issue by the plugin review team.

Just imagine how many errors/warnings bigger plugins will get because of that. They will be immediately scared off from using the Plugin Checker because it's just too much to handle.
