### ISSUE TITLE
Add `Server-Timing` to plugin action link for improved user experience

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/performance#799]
## Bug Description

During the review of issue #784, it was identified that the plugin action link lacks the Server-Timing. As a result, users face difficulty in effectively navigating and utilising the associated feature.

## Screenshots

<img width="998" alt="Screenshot 2023-08-10 at 10 22 18 AM" src="https://github.com/WordPress/performance/assets/10103365/a0be8931-faf9-4c9a-abc8-31ee1fd438cd">

**Comment by mukeshpanchal27** [comment]
CC. @felixarntz @joemcgill @eclarke1

**Comment by felixarntz** [comment]
Thanks @mukeshpanchal27 for the issue! Personally I'm not convinced we should add a link to the screen to the plugin entry, since it's not as crucial as the "Settings" screen. It's rather just an "advanced" tool, e.g. I think many users may not know what Server-Timing is and thus may not be able to make anything of that screen. So I was initially thinking not to link to it from elsewhere, e.g. not introduce an admin pointer for it either.

**Comment by mukeshpanchal27** [comment]
Thanks @felixarntz for the feedback. Make as close now. Thanks!
