### ISSUE TITLE
Conduct WP 6.5 Profiling Analysis

### ISSUE THREAD

**Issue by joemcgill** [WordPress/performance#874]
For previous WordPress releases, we've conducted a profiling analysis to see which functions account for the largest opportunity for improvement in server response times.

Previously: 
* [WP 6.2 analysis summary](https://make.wordpress.org/core/2023/05/25/wordpress-6-2-server-performance-analysis-summary/)
* [WP 6.3 profiling data](https://wordpress.slack.com/archives/C02KGN5K076/p1692132544354599)

## Objective

- [ ] Run another set of profiles for WP 6.5 using similar methodology as used previously
- [ ] Share raw data in a public sheet that others can review
- [ ] Write a summary of any observations, including future opportunities for improvement
- [ ] Create Trac tickets for any immediately actionable improvements.

**Comment by joemcgill** [comment]
Updating this to do for 6.5 after the release

**Comment by felixarntz** [comment]
@joemcgill While I believe the original purpose of this analysis was a general check on bottlenecks, after seeing that there are TTFB regressions in the 6.5 beta (per https://wordpress.slack.com/archives/C02KGN5K076/p1708701357471169), I think it would be great to conduct a profiling analysis focused on identifying where those regressions are coming from sooner than later.

Given the Performant Translations effort has landed in the release, it would be a much more appealing outcome if we could show the performance benefits of it at a glance, rather than having to explain something like "WP core isn't much faster for those localized sites despite Performant Translations, but only because there were regressions elsewhere" :)

cc @swissspidy

**Comment by westonruter** [comment]
Since 6.5 is now released, I think this can be closed. I believe this has been completed. I'm closing the WordPress 6.5 milestone.

**Comment by joemcgill** [comment]
This effort is actually to do a new analysis of 6.5 after the release is finished to look for new opportunities for performance improvements, so I’m going to reopen

**Comment by joemcgill** [comment]
We ended up not prioritizing a larger analysis for 6.5 either, so I'm closing. We can spin up a new issue for future versions.
