### ISSUE TITLE
 Update medium default image size 

### ISSUE THREAD

**Issue by adamsilverstein** [WordPress/performance#9]
* Suggestion is to change from 300px to 375px, we need to research further before deciding on image size. (suggested by Khôi Nguyễn Minh based on dimensions used in lighthouse tests)

**Comment by dainemawer** [comment]
Its interesting if you read the source code for `Properly size images` in Lighthouse:

```
/**
 * @fileoverview Checks to see if the images used on the page are larger than
 *   their display sizes. The audit will list all images that are larger than
 *   their display size with DPR (a 1000px wide image displayed as a
 *   500px high-res image on a Retina display is 100% used);
 *   However, the audit will only fail pages that use images that have waste
 *   beyond a particular byte threshold.
 */
```
In order to pass this test, we almost need to ensure that the image sizes are correct based on the `device-pixel-ratio`. As the example describes, `1000px` on a `@2x` screen is displayed at `500` so if we were to display `375px` then we need to ensure that a user uploads a `750px` image in order for their to be no waste

**Comment by adamsilverstein** [comment]
>  Suggestion is to change from 300px to 375px, we need to research further before deciding on image size. (suggested by Khôi Nguyễn Minh based on dimensions used in lighthouse tests)

Unfortunately, I opened this ticket without much context and it isn't really actionable as is. If the original reporter (Khôi Nguyễn Minh) had more details we might be able to work on it.  Its also possible our other work related to more accurate sizes will fix the reported issue.

In the meantime, I am closing this as "maybe later"
