### ISSUE TITLE
Store previous image size before `WebP` conversion

### ISSUE THREAD

**Issue by mitogh** [WordPress/performance#96]
As part of the set of measures we want to measure and use to comparison to know the real benefits of installing the plugin and enabling the modules, we need some sort of metrics as discussed  on: 

- #63 

For new and existing images as described in:

- #22 
- #24 

Storing the size of the image before the conversion would be helpful in order to run diff in size per image against the current image size and also an overall total in savings by using WebP images.

This can be done in all available image sizes as well in order to provide a better metric for the whole site instead. The ticket itself references the previous image size but it would be more accurate to store all previous image sizes available on the site before the conversion.

--- 

### Coments:

Slightly related to:

-  https://core.trac.wordpress.org/ticket/49412

_Originally posted by @mitogh in https://github.com/WordPress/performance/discussions/83#discussioncomment-1941502_

---

I know WordPress is about decisions not options, but I feel forcing image changes on websites without an easy way to opt out/in seems a bit heavy handed. Yes we are working towards a leaner internet, but forcing images to degrade (if that happens) or complicating the image loading experience for users will have a detrimental effect on adoption/continued usage of any platform.

I'd suggest keeping the original images as uploaded and processing the thumbnails with whatever format option is selected. If this option is ever changed then the thumbnails can be converted. User education is pretty clutch here as well.

_Originally posted by @ecotechie in https://github.com/WordPress/performance/discussions/83#discussioncomment-1949235_

---

I'm still in favor of the correct usage of the `<picture>` tag with `<img>` tags containing the correct `srcset` for both WebP and JPEG.  The companies that I work with are far more concerned with keeping backwards compatibility and page size than disk space.  Doing this would also allow for an additional image type as an early adoption eventually.  The supported image types could be configurable in either a performance settings page or in wp-config.php as a single option.  Any image clean up could be handled in WP CLI instead of on upload.

_Originally posted by @zero4281 in https://github.com/WordPress/performance/discussions/83#discussioncomment-1949293_

----

Removing old files seems a pretty bold move at these times. And even in the future.
The amount of storage should not be a concern (jpgs are small, webp even more).

_Originally posted by @GoyWebdesign in https://github.com/WordPress/performance/discussions/83#discussioncomment-1949825_

---

There are 3 possibilities then...

- Completely replace the uploaded image with a webp + generate webp resizes
- Keep a copy of the uploaded image and generate webp resizes
- Have a dual jpg/webp copy and serve the appropriate one to the client

I would prefer the second one, the support for webp is almost complete for all browsers and it doesn't make sense to keep a set of images that will remain unused. There's a chance that a small slice of browsers will be cut off but it's up to WordPress (since they do it on a large scale) to institute new standards that will force users to upgrade their browsers (but it's good since it's security and performance perspective)

> Removing old files seems a pretty bold move at these times

I even think that the old (and maybe useless) resizes should be deleted, once all resize images are converted to webp.

_Originally posted by @erikyo in https://github.com/WordPress/performance/discussions/83#discussioncomment-1955299_

---

### Links

- #70 
- #83

**Comment by adamsilverstein** [comment]
> There are 3 possibilities then...

> Completely replace the uploaded image with a webp + generate webp resizes
> Keep a copy of the uploaded image and generate webp resizes
> Have a dual jpg/webp copy and serve the appropriate one to the client

We need to keep the old images around (eg not delete them) to avoid breaking any existing links. Storing meta data about the old images could be useful for metrics, or maybe we could store some aggregate data about the change in image sizes.

Having `picture` element support would be fantastic, although for most users they can probably switch over to WebP since web browser support is excellent. One exception here is sites serving Newsletters or users with older MacOS Safari. I don't imagine that Outlooks supports the picture element so we may need to keep a reference to at least one jpeg (could be the original upload).

_The other part of image regeneration is getting the image sizes right._ When users change themes or plugins even, their sizes may change. So if the user has opted out of WebP by default, the behavior could be regenerating old JPEG images, but in new sizes.

**Comment by adamsilverstein** [comment]
A couple more thoughts:

> Completely replace the uploaded image with a webp + generate webp resizes
Whatever we decide about older sub sized images (delete or not delete), the default behavior should be filterable. Worth noting that WordPress never deletes the original image, so the sub sized jpegs could always be recreated if needed.

> Keep a copy of the uploaded image and generate webp resizes
This should be possible with a filter but maybe not the default behavior?

> Have a dual jpg/webp copy and serve the appropriate one to the client

This is a separate issue really, I'm not sure I see the value for WebP in particular. Once we are working on AVIF, this will become much more important though.

**Comment by hawilkins** [comment]
In response to:

> I'm still in favor of the correct usage of the <picture> tag with <img> tags containing the correct srcset for both WebP and JPEG. **The companies that I work with** are far more concerned with keeping backwards compatibility and page size than disk space. Doing this would also allow for an additional image type as an early adoption eventually. The supported image types could be configurable in either a performance settings page or in wp-config.php as a single option. **Any image clean up could be handled in WP CLI instead of on upload**.

Originally posted by @zero4281

WordPress is about everyone, not just _the companies you work with_, so storage space should be a consideration, as well as backwards compatibility. Users on shared hosting are going to care about disk space. 

Also, easily 90% or more of WordPress users have no clue what WP-CLI is, so assuming that image cleanup can be handled via WP-CLI is not an answer for handling image cleanup.

**Comment by zero4281** [comment]
@halounsbury I don't disagree with you at all.  This is why forcing the end users to do things a single way might not be a good idea and exactly why I suggest adding some options to the configuration, using the picture tag for backwards compatibility and flexibility.

**Comment by adamsilverstein** [comment]
I want to add that in what I consider the reference implementation, the "Regenerate Thumbnails" plugin https://wordpress.org/plugins/regenerate-thumbnails/ (installed on 1million+ sites) offers an option to "Delete thumbnail files for old unregistered sizes in order to free up server space. This may result in broken images in your posts and pages." which is **disabled by default**.

In #24 we are narrowly talking about a feature that converts existing `jpeg` images sub-sizes to `WebP`.  

Here is a single question we could vote on:

* When converting `jpeg` sub sizes to a new format (for example `WebP`):
	* should we by default delete the existing sub-size images... in order to free up server space (which might result in broken images in posts and pages)?


There are two other cases we can probably consider in separate issues and questions:
* When adding an additional mime type to existing sub sizes - for example adding `AVIF`  or `WebP` formats **in addition** to existing image sub sizes. Depends on `picture` element support to be useful.

* When regenerating the same mime type (to correct image size issues).

**Comment by adamsilverstein** [comment]
> WordPress is about everyone, not just the companies you work with, so storage space should be a consideration, as well as backwards compatibility. Users on shared hosting are going to care about disk space.

Good points @halounsbury - we will keep the hosting team updated in their chats about any potential changes (and how to opt in or out!) because often these decisions (the best default) are best made at that level. 

In addition, when choosing the default behavior (users will always be able to modify the default) it is worth remembering that part of our core philosophy (https://wordpress.org/about/philosophy/) is "Clean, Lean and Mean" ... "The rule of thumb is that the core should provide features that 80% or more of end users will actually appreciate and use". These features can only land in core if they truly benefit the majority of our users. That is probably why a regenerate thumbnails feature isn't in core yet.

**Comment by felixarntz** [comment]
Based on the conversation from Slack earlier today, the points mentioned above, and also based on the default behavior in the "Regenerate Thumbnails" plugin, I suggest the following:
1. When the user uploads a JPEG image, we generate the smaller image sizes in both JPEG and WebP by default.
2. When inserting an image into a post or including an image in the frontend through any other means, we use the WebP version whenever it is available.
3. Developers can opt out of generating JPEG _or_ WebP, e.g. if they are certain they won't need one of these versions.
4. This applies to new uploads, but the same would eventually apply to retroactive migration of images: Prefer WebP, but also keep having JPEG available.

Essentially, with the above, we'll move sites to exclusively rely on WebP in their frontend by default, as all browsers officially supported by WordPress support WebP. At the same time, we keep any extensions working which require JPEG versions, e.g. to include in emails where clients often do not support WebP. For the migration process specifically, this will furthermore ensure that any image links/references don't break, even if the migration process fails to update it to using the WebP version.

Curious to hear your thoughts. Since there are multiple related things to unpack here, let's keep the conversation focused: please refer to the numbered points above, e.g. if you agree with some but disagree with others.

cc @adamsilverstein

**Comment by adamsilverstein** [comment]
1. I like this for several reasons: 
 * we keep existing behavior (the jpegs), only enhancing it with the new WebP images
 * it gives the most flexibility and sets up for AVIF where this is arguably even more useful
1. The downside of this approach:
 * greatly increases storage requirements for uploading images
 * more than doubles already lengthy time to generate all of the image sub sizes
 * benefits are limited for most users since WebP support so widespread
 
Question: would generating only a single jpeg sub size (say 'large') be useful still? it would certainly alleviate what I see as the main downfalls of this approach.


Agree with 2, 3, 4 and would add  2 - use webp- when generating images dynamically (for example posts that display a featured image) or maybe block images?

**Comment by justlevine** [comment]
> Storing the size of the image before the conversion would be helpful in order to run diff in size per image against the current image size and also an overall total in savings by using WebP images.

This would be helpful not just for WebP, but the long standing [issue with generated PNGs as well](https://core.trac.wordpress.org/ticket/39236) where the smaller files can be even 2x as heavy as the original thanks to the upscaled bit depth

**Comment by felixarntz** [comment]
@adamsilverstein 
> * greatly increases storage requirements for uploading images
> * more than doubles already lengthy time to generate all of the image sub sizes
> * benefits are limited for most users since WebP support so widespread

Those are definitely crucial concerns, and that's where we have to weigh off benefits vs tradeoffs when making the decision for what the default behavior should be. But from my perspective being 100% safe in not breaking anything by keeping JPEG in addition to WebP is more valuable than those three concerns. In any case, sites that prefer it the other way, can customize the behavior e.g. via filter.

> Question: would generating only a single jpeg sub size (say 'large') be useful still? it would certainly alleviate what I see as the main downfalls of this approach.

I'm not sure this would be sufficient, since we don't know which image sizes e.g. plugins are using in whatever obscure ways. Since the main point of keeping generating JPEGs is to not break anything, I think we need to have them for all sizes. Per what I wrote above, I think that's okay since sites where this is a problem can still use a filter to adjust.

> Agree with 2, 3, 4 and would add 2 - use webp- when generating images dynamically (for example posts that display a featured image) or maybe block images?

Great point, I've now updated point 2 in my original comment to clarify that - it's about any images in the frontend really.

**Comment by mxbclang** [comment]
_Please vote for this approach with a thumbs-up or thumbs-down emoji. Voting will close on **1 Feb 2022 at 6pm GMT**._

Based on the conversation from Slack earlier today, the points mentioned above, and also based on the default behavior in the "Regenerate Thumbnails" plugin, I suggest the following:

1. When the user uploads a JPEG image, we generate the smaller image sizes in both JPEG and WebP by default.
2. When inserting an image into a post or including an image in the frontend through any other means, we use the WebP version whenever it is available.
3. Developers can opt out of generating JPEG or WebP, e.g. if they are certain they won't need one of these versions.
4. This applies to new uploads, but the same would eventually apply to retroactive migration of images: Prefer WebP, but also keep having JPEG available.

Essentially, with the above, we'll move sites to exclusively rely on WebP in their frontend by default, as all browsers officially supported by WordPress support WebP. At the same time, we keep any extensions working which require JPEG versions, e.g. to include in emails where clients often do not support WebP. For the migration process specifically, this will furthermore ensure that any image links/references don't break, even if the migration process fails to update it to using the WebP version.

Curious to hear your thoughts. Since there are multiple related things to unpack here, let's keep the conversation focused: please refer to the numbered points above, e.g. if you agree with some but disagree with others.

**Comment by mxbclang** [comment]
**Voting is now closed.**

Based on 16 thumbs up votes and no thumbs down votes, we'll proceed with this behavior:

1. When the user uploads a JPEG image, we generate the smaller image sizes in both JPEG and WebP by default.
2. When inserting an image into a post or including an image in the frontend through any other means, we use the WebP version whenever it is available.
3. Developers can opt out of generating JPEG or WebP, e.g. if they are certain they won't need one of these versions.
4. This applies to new uploads, but the same would eventually apply to retroactive migration of images: Prefer WebP, but also keep having JPEG available.

Removing Needs Decision. label and adding Needs Dev label.

**Comment by adamsilverstein** [comment]
Thanks everyone for your feedback here! Closing this issue as we will continue to work on this isn #142, #149 and other related tickets
